package com.qcap.cac.dao;

import java.util.List;
import java.util.Map;

import com.qcap.cac.model.TbSysLocation;
import org.springframework.stereotype.Repository;

/** 
 * @ClassName: LocationMapper 
 * @Description: TODO
 * @author: baojianxing
 * @date: 2018年4月25日 上午10:28:32  
 */
@Repository
public interface LocationMapper {

	/**
	 * 分页查询
	 * @Title: selectPp01ByPage 
	 * @Description: TODO
	 * @param mapParam
	 * @return
	 * @throws Exception
	 * @return: List<Map<String,Object>>
	 */
	public abstract List<Map<String, Object>> selectLocationByPage(Map<String, Object> mapParam) throws Exception;
	
    /**
     * 根据主键删除  软删除 修改的 delete_flag
     * @Title: deleteByPrimaryKey 
     * @Description: TODO
     * @param id
     * @return
     * @return: int
     */
    int deleteByPrimaryKey(String id);
    
    /**
	 * 修改地方名称
	 * @Title: updateLocationName 
	 * @Description: TODO
	 * @param map
	 * @throws Exception
	 * @return: void
	 */
	public void updateLocationName(Map map)throws Exception;

    /**
     * 添加
     * @Title: insert 
     * @Description: TODO
     * @param record
     * @return
     * @return: int
     */
    int insert(TbSysLocation record);
    
    /**
	 * 查询出所有的信息
	 * @Title: selectAll 
	 * @Description: TODO
	 * @return
	 * @throws Exception
	 * @return: List<Map<String,Object>>
	 */
	public List<Map<String,Object>> selectAll(Map param)throws Exception;
	
	/**
	 * 判断是否重名
	 * @Title: selectByName 
	 * @Description: TODO
	 * @param name
	 * @return
	 * @throws Exception
	 * @return: int
	 */
	public int selectByName(String name)throws Exception;
	
	/**
	 * 判断是否有孩子
	 * @Title: selectChild 
	 * @Description: TODO
	 * @param id
	 * @return
	 * @throws Exception
	 * @return: int
	 */
	public abstract int selectChild(String id)throws Exception;
	
	/**
	 * 新增：判断是否有子部门 
	 * @Title: queryChildDept 
	 * @Description: TODO
	 * @param tbbb04Id
	 * @return
	 * @throws Exception
	 * @return: String
	 */
	public abstract String queryChildLocation(String id)throws Exception;

	/**
	 * 查询最后的Id
	 * @Title: selectMaxId 
	 * @Description: TODO
	 * @param pId
	 * @return
	 * @throws Exception
	 * @return: String
	 */
	public abstract String selectMaxId(String pId )throws Exception;

   /**
    * 根据主键查询
    * @Title: selectByPrimaryKey 
    * @Description: TODO
    * @param id
    * @return
    * @return: TbSysLocation
    */
    TbSysLocation selectByPrimaryKey(String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_location
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    int updateByPrimaryKey(TbSysLocation record);
	
}
