server:
  port: 8060
  servlet:  
    context-path: /cac
spring:
  datasource:
    url: jdbc:mysql://192.168.1.92:3306/cac?zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    password: Admin@2018dzwy
    username: cac
    druid:
      max-pool-prepared-statement-per-connection-size: 20
      min-idle: 5
      max-active: 200
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 'x'
      use-global-data-source-stat: true
      filters: stat,wall,slf4j
      max-wait: 60000
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      test-on-borrow: false
      pool-prepared-statements: false
      initial-size: 5
      min-evictable-idle-time-millis: 300000
      test-on-return: false
  session:
    store-type: none
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      maxRequestSize: 100MB
      maxFileSize: 100MB
  redis:
    host: 192.168.1.184
    password: whxx123.
    database: 0
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    timeout: 5000ms
mybatis-plus:
  type-aliases-package: com.qcap.*.model, com.qcap.*.entity
  mapper-locations: classpath:/com/qcap/*/mapper/*.xml
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
      capital-mode: false
      column-underline: true
  configuration:
    cache-enabled:  false
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback-prod.xml

rest:
  restfulSign: /rest
  coreOpen: true
  swaggerEnable: false
mybatis:
  mapper-refresh: true
  iPage:
    page-parameter: page
    size-parameter: size

#fastdfs配置
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:
    width: 150
    height: 150
  trackerList:
    - 192.168.1.226:22122