package com.qcap.cac.entity;

import com.baomidou.mybatisplus.annotation.TableId;

import java.util.Date;

public class TbAreaPosition {
    /**
    *   主键
     */
    @TableId("POSITION_ID")
    private String positionId;

    /**
    *   岗位编码
     */
    private String positionCode;

    /**
     *   岗位类型
     */
    private String positionType;

    /**
    *   岗位名称
     */
    private String positionName;

    /**
     *   岗位二维码URL
     */
    private String positionUrl;

    /**
    *   区域名称
     */
    private String areaName;

    /**
    *   区域编码
     */
    private String areaCode;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    public String getPositionType() {
        return positionType;
    }

    public void setPositionType(String positionType) {
        this.positionType = positionType;
    }

    public String getPositionUrl() {
        return positionUrl;
    }

    public void setPositionUrl(String positionUrl) {
        this.positionUrl = positionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.POSITION_ID
     *
     * @return the value of tb_area_position.POSITION_ID
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.POSITION_ID
     *
     * @param positionId the value for tb_area_position.POSITION_ID
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setPositionId(String positionId) {
        this.positionId = positionId == null ? null : positionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.POSITION_CODE
     *
     * @return the value of tb_area_position.POSITION_CODE
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getPositionCode() {
        return positionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.POSITION_CODE
     *
     * @param positionCode the value for tb_area_position.POSITION_CODE
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setPositionCode(String positionCode) {
        this.positionCode = positionCode == null ? null : positionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.POSITION_NAME
     *
     * @return the value of tb_area_position.POSITION_NAME
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.POSITION_NAME
     *
     * @param positionName the value for tb_area_position.POSITION_NAME
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.AREA_NAME
     *
     * @return the value of tb_area_position.AREA_NAME
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.AREA_NAME
     *
     * @param areaName the value for tb_area_position.AREA_NAME
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.AREA_CODE
     *
     * @return the value of tb_area_position.AREA_CODE
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.AREA_CODE
     *
     * @param areaCode the value for tb_area_position.AREA_CODE
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.REMARK1
     *
     * @return the value of tb_area_position.REMARK1
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.REMARK1
     *
     * @param remark1 the value for tb_area_position.REMARK1
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.REMARK2
     *
     * @return the value of tb_area_position.REMARK2
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.REMARK2
     *
     * @param remark2 the value for tb_area_position.REMARK2
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.REMARK3
     *
     * @return the value of tb_area_position.REMARK3
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.REMARK3
     *
     * @param remark3 the value for tb_area_position.REMARK3
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.CREATE_EMP
     *
     * @return the value of tb_area_position.CREATE_EMP
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.CREATE_EMP
     *
     * @param createEmp the value for tb_area_position.CREATE_EMP
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.CREATE_DATE
     *
     * @return the value of tb_area_position.CREATE_DATE
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.CREATE_DATE
     *
     * @param createDate the value for tb_area_position.CREATE_DATE
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.UPDATE_DATE
     *
     * @return the value of tb_area_position.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.UPDATE_DATE
     *
     * @param updateDate the value for tb_area_position.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.UPDATE_EMP
     *
     * @return the value of tb_area_position.UPDATE_EMP
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.UPDATE_EMP
     *
     * @param updateEmp the value for tb_area_position.UPDATE_EMP
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_position.VERSION
     *
     * @return the value of tb_area_position.VERSION
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_position.VERSION
     *
     * @param version the value for tb_area_position.VERSION
     *
     * @mbggenerated Wed Oct 10 09:25:52 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}