package com.qcap.cac.entity;

import java.util.Date;

public class TbAreaStandardDetail {
    /**
    *   主键
     */
    private String standardDetailId;

    /**
    *   标准主表编码
     */
    private String standardCode;

    /**
    *   材质
     */
    private String material;

    /**
    *   步骤
     */
    private String standardStep;

    /**
    *   设备类型
     */
    private String equitmetType;

    /**
    *   用具
     */
    private String cleanTools;

    /**
    *   标准清洁要求
     */
    private String standardRequirement;

    /**
    *   图片地址
     */
    private String imgUrl;

    /**
    *   文件地址
     */
    private String fileUrl;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.STANDARD_DETAIL_ID
     *
     * @return the value of tb_area_standard_detail.STANDARD_DETAIL_ID
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getStandardDetailId() {
        return standardDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.STANDARD_DETAIL_ID
     *
     * @param standardDetailId the value for tb_area_standard_detail.STANDARD_DETAIL_ID
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setStandardDetailId(String standardDetailId) {
        this.standardDetailId = standardDetailId == null ? null : standardDetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.STANDARD_CODE
     *
     * @return the value of tb_area_standard_detail.STANDARD_CODE
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getStandardCode() {
        return standardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.STANDARD_CODE
     *
     * @param standardCode the value for tb_area_standard_detail.STANDARD_CODE
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setStandardCode(String standardCode) {
        this.standardCode = standardCode == null ? null : standardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.MATERIAL
     *
     * @return the value of tb_area_standard_detail.MATERIAL
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.MATERIAL
     *
     * @param material the value for tb_area_standard_detail.MATERIAL
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.STANDARD_STEP
     *
     * @return the value of tb_area_standard_detail.STANDARD_STEP
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getStandardStep() {
        return standardStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.STANDARD_STEP
     *
     * @param standardStep the value for tb_area_standard_detail.STANDARD_STEP
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setStandardStep(String standardStep) {
        this.standardStep = standardStep == null ? null : standardStep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.EQUITMET_TYPE
     *
     * @return the value of tb_area_standard_detail.EQUITMET_TYPE
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getEquitmetType() {
        return equitmetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.EQUITMET_TYPE
     *
     * @param equitmetType the value for tb_area_standard_detail.EQUITMET_TYPE
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setEquitmetType(String equitmetType) {
        this.equitmetType = equitmetType == null ? null : equitmetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.CLEAN_TOOLS
     *
     * @return the value of tb_area_standard_detail.CLEAN_TOOLS
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getCleanTools() {
        return cleanTools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.CLEAN_TOOLS
     *
     * @param cleanTools the value for tb_area_standard_detail.CLEAN_TOOLS
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setCleanTools(String cleanTools) {
        this.cleanTools = cleanTools == null ? null : cleanTools.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.STANDARD_REQUIREMENT
     *
     * @return the value of tb_area_standard_detail.STANDARD_REQUIREMENT
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getStandardRequirement() {
        return standardRequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.STANDARD_REQUIREMENT
     *
     * @param standardRequirement the value for tb_area_standard_detail.STANDARD_REQUIREMENT
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setStandardRequirement(String standardRequirement) {
        this.standardRequirement = standardRequirement == null ? null : standardRequirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.IMG_URL
     *
     * @return the value of tb_area_standard_detail.IMG_URL
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.IMG_URL
     *
     * @param imgUrl the value for tb_area_standard_detail.IMG_URL
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.FILE_URL
     *
     * @return the value of tb_area_standard_detail.FILE_URL
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.FILE_URL
     *
     * @param fileUrl the value for tb_area_standard_detail.FILE_URL
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.REMARK1
     *
     * @return the value of tb_area_standard_detail.REMARK1
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.REMARK1
     *
     * @param remark1 the value for tb_area_standard_detail.REMARK1
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.REMARK2
     *
     * @return the value of tb_area_standard_detail.REMARK2
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.REMARK2
     *
     * @param remark2 the value for tb_area_standard_detail.REMARK2
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.REMARK3
     *
     * @return the value of tb_area_standard_detail.REMARK3
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.REMARK3
     *
     * @param remark3 the value for tb_area_standard_detail.REMARK3
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.CREATE_EMP
     *
     * @return the value of tb_area_standard_detail.CREATE_EMP
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.CREATE_EMP
     *
     * @param createEmp the value for tb_area_standard_detail.CREATE_EMP
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.CREATE_DATE
     *
     * @return the value of tb_area_standard_detail.CREATE_DATE
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.CREATE_DATE
     *
     * @param createDate the value for tb_area_standard_detail.CREATE_DATE
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.UPDATE_DATE
     *
     * @return the value of tb_area_standard_detail.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.UPDATE_DATE
     *
     * @param updateDate the value for tb_area_standard_detail.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.UPDATE_EMP
     *
     * @return the value of tb_area_standard_detail.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.UPDATE_EMP
     *
     * @param updateEmp the value for tb_area_standard_detail.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area_standard_detail.VERSION
     *
     * @return the value of tb_area_standard_detail.VERSION
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area_standard_detail.VERSION
     *
     * @param version the value for tb_area_standard_detail.VERSION
     *
     * @mbggenerated Tue Oct 16 20:03:37 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}