package com.qcap.cac.entity;

import java.io.Serializable;
import java.util.Date;

public class TbFlightInfo implements Serializable {
    /**
	 * @fieldName: serialVersionUID
	 * @fieldType: long
	 * @Description: TODO
	 */
	private static final long serialVersionUID = 492680713001416620L;

	/**
    *   主键
     */
    private String flightInfoId;

    /**
    *   航班号
     */
    private String fligntName;

    /**
    *   事件类型
     */
    private String eventType;

    /**
    *   航班类型
     */
    private String flightType;

    /**
    *   登机口
     */
    private String departureGate;

    /**
    *   保障等级
     */
    private String guaranteeType;

    /**
    *   计划起飞、到达时间
     */
    private Date planningTakeoffTime;

    /**
    *   预计起飞/到达时间
     */
    private Date estimatedTakeoffTime;

    /**
    *   机型
     */
    private String aircraftType;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.FLIGHT_INFO_ID
     *
     * @return the value of tb_flight_info.FLIGHT_INFO_ID
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getFlightInfoId() {
        return flightInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.FLIGHT_INFO_ID
     *
     * @param flightInfoId the value for tb_flight_info.FLIGHT_INFO_ID
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setFlightInfoId(String flightInfoId) {
        this.flightInfoId = flightInfoId == null ? null : flightInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.FLIGNT_NAME
     *
     * @return the value of tb_flight_info.FLIGNT_NAME
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getFligntName() {
        return fligntName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.FLIGNT_NAME
     *
     * @param fligntName the value for tb_flight_info.FLIGNT_NAME
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setFligntName(String fligntName) {
        this.fligntName = fligntName == null ? null : fligntName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.EVENT_TYPE
     *
     * @return the value of tb_flight_info.EVENT_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.EVENT_TYPE
     *
     * @param eventType the value for tb_flight_info.EVENT_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.FLIGHT_TYPE
     *
     * @return the value of tb_flight_info.FLIGHT_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getFlightType() {
        return flightType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.FLIGHT_TYPE
     *
     * @param flightType the value for tb_flight_info.FLIGHT_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setFlightType(String flightType) {
        this.flightType = flightType == null ? null : flightType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.DEPARTURE_GATE
     *
     * @return the value of tb_flight_info.DEPARTURE_GATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getDepartureGate() {
        return departureGate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.DEPARTURE_GATE
     *
     * @param departureGate the value for tb_flight_info.DEPARTURE_GATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setDepartureGate(String departureGate) {
        this.departureGate = departureGate == null ? null : departureGate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.GUARANTEE_TYPE
     *
     * @return the value of tb_flight_info.GUARANTEE_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getGuaranteeType() {
        return guaranteeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.GUARANTEE_TYPE
     *
     * @param guaranteeType the value for tb_flight_info.GUARANTEE_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setGuaranteeType(String guaranteeType) {
        this.guaranteeType = guaranteeType == null ? null : guaranteeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.PLANNING_TAKEOFF_TIME
     *
     * @return the value of tb_flight_info.PLANNING_TAKEOFF_TIME
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public Date getPlanningTakeoffTime() {
        return planningTakeoffTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.PLANNING_TAKEOFF_TIME
     *
     * @param planningTakeoffTime the value for tb_flight_info.PLANNING_TAKEOFF_TIME
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setPlanningTakeoffTime(Date planningTakeoffTime) {
        this.planningTakeoffTime = planningTakeoffTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.ESTIMATED_TAKEOFF_TIME
     *
     * @return the value of tb_flight_info.ESTIMATED_TAKEOFF_TIME
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public Date getEstimatedTakeoffTime() {
        return estimatedTakeoffTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.ESTIMATED_TAKEOFF_TIME
     *
     * @param estimatedTakeoffTime the value for tb_flight_info.ESTIMATED_TAKEOFF_TIME
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setEstimatedTakeoffTime(Date estimatedTakeoffTime) {
        this.estimatedTakeoffTime = estimatedTakeoffTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.AIRCRAFT_TYPE
     *
     * @return the value of tb_flight_info.AIRCRAFT_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getAircraftType() {
        return aircraftType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.AIRCRAFT_TYPE
     *
     * @param aircraftType the value for tb_flight_info.AIRCRAFT_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setAircraftType(String aircraftType) {
        this.aircraftType = aircraftType == null ? null : aircraftType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.REMARK1
     *
     * @return the value of tb_flight_info.REMARK1
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.REMARK1
     *
     * @param remark1 the value for tb_flight_info.REMARK1
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.REMARK2
     *
     * @return the value of tb_flight_info.REMARK2
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.REMARK2
     *
     * @param remark2 the value for tb_flight_info.REMARK2
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.REMARK3
     *
     * @return the value of tb_flight_info.REMARK3
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.REMARK3
     *
     * @param remark3 the value for tb_flight_info.REMARK3
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.CREATE_EMP
     *
     * @return the value of tb_flight_info.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.CREATE_EMP
     *
     * @param createEmp the value for tb_flight_info.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.CREATE_DATE
     *
     * @return the value of tb_flight_info.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.CREATE_DATE
     *
     * @param createDate the value for tb_flight_info.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.UPDATE_DATE
     *
     * @return the value of tb_flight_info.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.UPDATE_DATE
     *
     * @param updateDate the value for tb_flight_info.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.UPDATE_EMP
     *
     * @return the value of tb_flight_info.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.UPDATE_EMP
     *
     * @param updateEmp the value for tb_flight_info.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_flight_info.VERSION
     *
     * @return the value of tb_flight_info.VERSION
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_flight_info.VERSION
     *
     * @param version the value for tb_flight_info.VERSION
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}