package com.qcap.cac.entity;

import java.io.Serializable;
import java.util.Date;

public class TbPlan implements Serializable {
	/**
	 * @fieldName: serialVersionUID
	 * @fieldType: long
	 * @Description: TODO
	 */
	private static final long serialVersionUID = 3203807233928730729L;

	/**
	 * 主键
	 */
	private String planId;

	/**
	 * 区域编码
	 */
	private String areaCode;

	/**
	 * 标准编码
	 */
	private String standardCode;

	/**
	 * 时间类型
	 */
	private String planTimeType;

	/**
	 * 月份
	 */
	private String month;

	/**
	 * 日期
	 */
	private String day;

	/**
	 * 周
	 */
	private String week;

	/**
	 * 开始时间
	 */
	private String startTime;

	/**
	 * 截止时间
	 */
	private String endTime;

	/**
	 * 上次任务完成时间
	 */
	private Date prevTaskDoneDate;

	/**
	 * 备注1
	 */
	private String remark1;

	/**
	 * 备注2
	 */
	private String remark2;

	/**
	 * 备注3
	 */
	private String remark3;

	/**
	 * 新增人
	 */
	private String createEmp;

	/**
	 * 新增时间
	 */
	private Date createDate;

	/**
	 * 修改时间
	 */
	private Date updateDate;

	/**
	 * 修改人
	 */
	private String updateEmp;

	/**
	 * 版本
	 */
	private Integer version;

	private String checkFlag;

	private String uploadPicFlag;

	private String startScanFlag;

	private String endScanFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.PLAN_ID
	 *
	 * @return the value of tb_plan.PLAN_ID
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getPlanId() {
		return planId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.PLAN_ID
	 *
	 * @param planId
	 *            the value for tb_plan.PLAN_ID
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setPlanId(String planId) {
		this.planId = planId == null ? null : planId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.AREA_CODE
	 *
	 * @return the value of tb_plan.AREA_CODE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getAreaCode() {
		return areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.AREA_CODE
	 *
	 * @param areaCode
	 *            the value for tb_plan.AREA_CODE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode == null ? null : areaCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.STANDARD_CODE
	 *
	 * @return the value of tb_plan.STANDARD_CODE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getStandardCode() {
		return standardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.STANDARD_CODE
	 *
	 * @param standardCode
	 *            the value for tb_plan.STANDARD_CODE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setStandardCode(String standardCode) {
		this.standardCode = standardCode == null ? null : standardCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.PLAN_TIME_TYPE
	 *
	 * @return the value of tb_plan.PLAN_TIME_TYPE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getPlanTimeType() {
		return planTimeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.PLAN_TIME_TYPE
	 *
	 * @param planTimeType
	 *            the value for tb_plan.PLAN_TIME_TYPE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setPlanTimeType(String planTimeType) {
		this.planTimeType = planTimeType == null ? null : planTimeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.MONTH
	 *
	 * @return the value of tb_plan.MONTH
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getMonth() {
		return month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.MONTH
	 *
	 * @param month
	 *            the value for tb_plan.MONTH
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setMonth(String month) {
		this.month = month == null ? null : month.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.DAY
	 *
	 * @return the value of tb_plan.DAY
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getDay() {
		return day;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.DAY
	 *
	 * @param day
	 *            the value for tb_plan.DAY
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setDay(String day) {
		this.day = day == null ? null : day.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.WEEK
	 *
	 * @return the value of tb_plan.WEEK
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getWeek() {
		return week;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.WEEK
	 *
	 * @param week
	 *            the value for tb_plan.WEEK
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setWeek(String week) {
		this.week = week == null ? null : week.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.START_TIME
	 *
	 * @return the value of tb_plan.START_TIME
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.START_TIME
	 *
	 * @param startTime
	 *            the value for tb_plan.START_TIME
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime == null ? null : startTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.END_TIME
	 *
	 * @return the value of tb_plan.END_TIME
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.END_TIME
	 *
	 * @param endTime
	 *            the value for tb_plan.END_TIME
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime == null ? null : endTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.PREV_TASK_DONE_DATE
	 *
	 * @return the value of tb_plan.PREV_TASK_DONE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public Date getPrevTaskDoneDate() {
		return prevTaskDoneDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.PREV_TASK_DONE_DATE
	 *
	 * @param prevTaskDoneDate
	 *            the value for tb_plan.PREV_TASK_DONE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setPrevTaskDoneDate(Date prevTaskDoneDate) {
		this.prevTaskDoneDate = prevTaskDoneDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.REMARK1
	 *
	 * @return the value of tb_plan.REMARK1
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getRemark1() {
		return remark1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.REMARK1
	 *
	 * @param remark1
	 *            the value for tb_plan.REMARK1
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setRemark1(String remark1) {
		this.remark1 = remark1 == null ? null : remark1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.REMARK2
	 *
	 * @return the value of tb_plan.REMARK2
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getRemark2() {
		return remark2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.REMARK2
	 *
	 * @param remark2
	 *            the value for tb_plan.REMARK2
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setRemark2(String remark2) {
		this.remark2 = remark2 == null ? null : remark2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.REMARK3
	 *
	 * @return the value of tb_plan.REMARK3
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getRemark3() {
		return remark3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.REMARK3
	 *
	 * @param remark3
	 *            the value for tb_plan.REMARK3
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setRemark3(String remark3) {
		this.remark3 = remark3 == null ? null : remark3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.CREATE_EMP
	 *
	 * @return the value of tb_plan.CREATE_EMP
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getCreateEmp() {
		return createEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.CREATE_EMP
	 *
	 * @param createEmp
	 *            the value for tb_plan.CREATE_EMP
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setCreateEmp(String createEmp) {
		this.createEmp = createEmp == null ? null : createEmp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.CREATE_DATE
	 *
	 * @return the value of tb_plan.CREATE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.CREATE_DATE
	 *
	 * @param createDate
	 *            the value for tb_plan.CREATE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.UPDATE_DATE
	 *
	 * @return the value of tb_plan.UPDATE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.UPDATE_DATE
	 *
	 * @param updateDate
	 *            the value for tb_plan.UPDATE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.UPDATE_EMP
	 *
	 * @return the value of tb_plan.UPDATE_EMP
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getUpdateEmp() {
		return updateEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.UPDATE_EMP
	 *
	 * @param updateEmp
	 *            the value for tb_plan.UPDATE_EMP
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setUpdateEmp(String updateEmp) {
		this.updateEmp = updateEmp == null ? null : updateEmp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan.VERSION
	 *
	 * @return the value of tb_plan.VERSION
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan.VERSION
	 *
	 * @param version
	 *            the value for tb_plan.VERSION
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getCheckFlag() {
		return checkFlag;
	}

	public void setCheckFlag(String checkFlag) {
		this.checkFlag = checkFlag;
	}

	public String getUploadPicFlag() {
		return uploadPicFlag;
	}

	public void setUploadPicFlag(String uploadPicFlag) {
		this.uploadPicFlag = uploadPicFlag;
	}

	public String getStartScanFlag() {
		return startScanFlag;
	}

	public void setStartScanFlag(String startScanFlag) {
		this.startScanFlag = startScanFlag;
	}

	public String getEndScanFlag() {
		return endScanFlag;
	}

	public void setEndScanFlag(String endScanFlag) {
		this.endScanFlag = endScanFlag;
	}

}