package com.qcap.cac.entity;

import java.io.Serializable;
import java.util.Date;

public class TbPlanEvent implements Serializable {
	/**
	 * @fieldName: serialVersionUID
	 * @fieldType: long
	 * @Description: TODO
	 */
	private static final long serialVersionUID = -778783694990952579L;

	/**
	 * 主键
	 */
	private String planEventId;

	/**
	 * 主键
	 */
	private String programCode;

	/**
	 * 区域编码
	 */
	private String areaCode;

	/**
	 * 标准编码
	 */
	private String standardCode;

	/**
	 * 事件类型
	 */
	private String eventType;

	/**
	 * 保障等级
	 */
	private String guaranteeType;

	/**
	 * 备注1
	 */
	private String remark1;

	/**
	 * 备注2
	 */
	private String remark2;

	/**
	 * 备注3
	 */
	private String remark3;

	/**
	 * 新增人
	 */
	private String createEmp;

	/**
	 * 新增时间
	 */
	private Date createDate;

	/**
	 * 修改时间
	 */
	private Date updateDate;

	/**
	 * 修改人
	 */
	private String updateEmp;

	/**
	 * 版本
	 */
	private Integer version;

	private String checkFlag;

	private String uploadPicFlag;

	private String startScanFlag;

	private String endScanFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.PLAN_EVENT_ID
	 *
	 * @return the value of tb_plan_event.PLAN_EVENT_ID
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getPlanEventId() {
		return planEventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.PLAN_EVENT_ID
	 *
	 * @param planEventId
	 *            the value for tb_plan_event.PLAN_EVENT_ID
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setPlanEventId(String planEventId) {
		this.planEventId = planEventId == null ? null : planEventId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.AREA_CODE
	 *
	 * @return the value of tb_plan_event.AREA_CODE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getAreaCode() {
		return areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.AREA_CODE
	 *
	 * @param areaCode
	 *            the value for tb_plan_event.AREA_CODE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode == null ? null : areaCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.STANDARD_CODE
	 *
	 * @return the value of tb_plan_event.STANDARD_CODE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getStandardCode() {
		return standardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.STANDARD_CODE
	 *
	 * @param standardCode
	 *            the value for tb_plan_event.STANDARD_CODE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setStandardCode(String standardCode) {
		this.standardCode = standardCode == null ? null : standardCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.EVENT_TYPE
	 *
	 * @return the value of tb_plan_event.EVENT_TYPE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getEventType() {
		return eventType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.EVENT_TYPE
	 *
	 * @param eventType
	 *            the value for tb_plan_event.EVENT_TYPE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setEventType(String eventType) {
		this.eventType = eventType == null ? null : eventType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.GUARANTEE_TYPE
	 *
	 * @return the value of tb_plan_event.GUARANTEE_TYPE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getGuaranteeType() {
		return guaranteeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.GUARANTEE_TYPE
	 *
	 * @param guaranteeType
	 *            the value for tb_plan_event.GUARANTEE_TYPE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setGuaranteeType(String guaranteeType) {
		this.guaranteeType = guaranteeType == null ? null : guaranteeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.REMARK1
	 *
	 * @return the value of tb_plan_event.REMARK1
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getRemark1() {
		return remark1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.REMARK1
	 *
	 * @param remark1
	 *            the value for tb_plan_event.REMARK1
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setRemark1(String remark1) {
		this.remark1 = remark1 == null ? null : remark1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.REMARK2
	 *
	 * @return the value of tb_plan_event.REMARK2
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getRemark2() {
		return remark2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.REMARK2
	 *
	 * @param remark2
	 *            the value for tb_plan_event.REMARK2
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setRemark2(String remark2) {
		this.remark2 = remark2 == null ? null : remark2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.REMARK3
	 *
	 * @return the value of tb_plan_event.REMARK3
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getRemark3() {
		return remark3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.REMARK3
	 *
	 * @param remark3
	 *            the value for tb_plan_event.REMARK3
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setRemark3(String remark3) {
		this.remark3 = remark3 == null ? null : remark3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.CREATE_EMP
	 *
	 * @return the value of tb_plan_event.CREATE_EMP
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getCreateEmp() {
		return createEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.CREATE_EMP
	 *
	 * @param createEmp
	 *            the value for tb_plan_event.CREATE_EMP
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setCreateEmp(String createEmp) {
		this.createEmp = createEmp == null ? null : createEmp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.CREATE_DATE
	 *
	 * @return the value of tb_plan_event.CREATE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.CREATE_DATE
	 *
	 * @param createDate
	 *            the value for tb_plan_event.CREATE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.UPDATE_DATE
	 *
	 * @return the value of tb_plan_event.UPDATE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.UPDATE_DATE
	 *
	 * @param updateDate
	 *            the value for tb_plan_event.UPDATE_DATE
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.UPDATE_EMP
	 *
	 * @return the value of tb_plan_event.UPDATE_EMP
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public String getUpdateEmp() {
		return updateEmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.UPDATE_EMP
	 *
	 * @param updateEmp
	 *            the value for tb_plan_event.UPDATE_EMP
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setUpdateEmp(String updateEmp) {
		this.updateEmp = updateEmp == null ? null : updateEmp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_plan_event.VERSION
	 *
	 * @return the value of tb_plan_event.VERSION
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_plan_event.VERSION
	 *
	 * @param version
	 *            the value for tb_plan_event.VERSION
	 *
	 * @mbggenerated Tue Oct 09 15:30:51 CST 2018
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getCheckFlag() {
		return checkFlag;
	}

	public void setCheckFlag(String checkFlag) {
		this.checkFlag = checkFlag;
	}

	public String getUploadPicFlag() {
		return uploadPicFlag;
	}

	public void setUploadPicFlag(String uploadPicFlag) {
		this.uploadPicFlag = uploadPicFlag;
	}

	public String getStartScanFlag() {
		return startScanFlag;
	}

	public void setStartScanFlag(String startScanFlag) {
		this.startScanFlag = startScanFlag;
	}

	public String getEndScanFlag() {
		return endScanFlag;
	}

	public void setEndScanFlag(String endScanFlag) {
		this.endScanFlag = endScanFlag;
	}

	public String getProgramCode() {
		return programCode;
	}

	public void setProgramCode(String programCode) {
		this.programCode = programCode;
	}
}