package com.qcap.cac.entity;

import java.util.Date;

public class TbSysFile {
    /**
    *   主键
     */
    private String fileId;

    /**
    *   文件上级ID
     */
    private String groupId;

    /**
    *   文件名称
     */
    private String fileName;

    /**
    *   文件类型
     */
    private String fileType;

    /**
    *   存储路径
     */
    private String storeUrl;

    /**
    *   访问路径
     */
    private String downloadUrl;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.FILE_ID
     *
     * @return the value of tb_sys_file.FILE_ID
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.FILE_ID
     *
     * @param fileId the value for tb_sys_file.FILE_ID
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.GROUP_ID
     *
     * @return the value of tb_sys_file.GROUP_ID
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.GROUP_ID
     *
     * @param groupId the value for tb_sys_file.GROUP_ID
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.FILE_NAME
     *
     * @return the value of tb_sys_file.FILE_NAME
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.FILE_NAME
     *
     * @param fileName the value for tb_sys_file.FILE_NAME
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.FILE_TYPE
     *
     * @return the value of tb_sys_file.FILE_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.FILE_TYPE
     *
     * @param fileType the value for tb_sys_file.FILE_TYPE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.STORE_URL
     *
     * @return the value of tb_sys_file.STORE_URL
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getStoreUrl() {
        return storeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.STORE_URL
     *
     * @param storeUrl the value for tb_sys_file.STORE_URL
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setStoreUrl(String storeUrl) {
        this.storeUrl = storeUrl == null ? null : storeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.DOWNLOAD_URL
     *
     * @return the value of tb_sys_file.DOWNLOAD_URL
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.DOWNLOAD_URL
     *
     * @param downloadUrl the value for tb_sys_file.DOWNLOAD_URL
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.REMARK1
     *
     * @return the value of tb_sys_file.REMARK1
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.REMARK1
     *
     * @param remark1 the value for tb_sys_file.REMARK1
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.REMARK2
     *
     * @return the value of tb_sys_file.REMARK2
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.REMARK2
     *
     * @param remark2 the value for tb_sys_file.REMARK2
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.REMARK3
     *
     * @return the value of tb_sys_file.REMARK3
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.REMARK3
     *
     * @param remark3 the value for tb_sys_file.REMARK3
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.CREATE_EMP
     *
     * @return the value of tb_sys_file.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.CREATE_EMP
     *
     * @param createEmp the value for tb_sys_file.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.CREATE_DATE
     *
     * @return the value of tb_sys_file.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.CREATE_DATE
     *
     * @param createDate the value for tb_sys_file.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.UPDATE_DATE
     *
     * @return the value of tb_sys_file.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.UPDATE_DATE
     *
     * @param updateDate the value for tb_sys_file.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.UPDATE_EMP
     *
     * @return the value of tb_sys_file.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.UPDATE_EMP
     *
     * @param updateEmp the value for tb_sys_file.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_file.VERSION
     *
     * @return the value of tb_sys_file.VERSION
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_file.VERSION
     *
     * @param version the value for tb_sys_file.VERSION
     *
     * @mbggenerated Tue Oct 09 15:30:51 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}