package com.qcap.cac.entity;

import java.io.Serializable;
import java.util.Date;

public class TbTaskArrangement implements Serializable {
    /**
	 * @fieldName: serialVersionUID
	 * @fieldType: long
	 * @Description: TODO
	 */
	private static final long serialVersionUID = -6316486697074649415L;

	/**
    *   主键
     */
    private String arrangementId;

    /**
    *   班次
     */
    private String shift;

    /**
    *   员工编号
     */
    private String employeeCode;

    /**
    *   员工姓名
     */
    private String employeeName;

    /**
    *   员工电话
     */
    private String employeeTel;

    /**
    *   岗位ID
     */
    private String positionCode;

    /**
    *   岗位名称
     */
    private String positionName;

    /**
    *   月份
     */
    private String month;

    /**
    *   删除标识
     */
    private String deleteFlag;

    /**
    *   1号
     */
    private String day1;

    /**
    *   2号
     */
    private String day2;

    /**
    *   3号
     */
    private String day3;

    /**
    *   4号
     */
    private String day4;

    /**
    *   5号
     */
    private String day5;

    /**
    *   6号
     */
    private String day6;

    /**
    *   7号
     */
    private String day7;

    /**
    *   8号
     */
    private String day8;

    /**
    *   9号
     */
    private String day9;

    /**
    *   10号
     */
    private String day10;

    /**
    *   11号
     */
    private String day11;

    /**
    *   12号
     */
    private String day12;

    /**
    *   13号
     */
    private String day13;

    /**
    *   14号
     */
    private String day14;

    /**
    *   15号
     */
    private String day15;

    /**
    *   16号
     */
    private String day16;

    /**
    *   17号
     */
    private String day17;

    /**
    *   18号
     */
    private String day18;

    /**
    *   19号
     */
    private String day19;

    /**
    *   20号
     */
    private String day20;

    /**
    *   21号
     */
    private String day21;

    /**
    *   22号
     */
    private String day22;

    /**
    *   23号
     */
    private String day23;

    /**
    *   24号
     */
    private String day24;

    /**
    *   25号
     */
    private String day25;

    /**
    *   26号
     */
    private String day26;

    /**
    *   27号
     */
    private String day27;

    /**
    *   28号
     */
    private String day28;

    /**
    *   29号
     */
    private String day29;

    /**
    *   30号
     */
    private String day30;

    /**
    *   31号
     */
    private String day31;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.ARRANGEMENT_ID
     *
     * @return the value of tb_task_arrangement.ARRANGEMENT_ID
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getArrangementId() {
        return arrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.ARRANGEMENT_ID
     *
     * @param arrangementId the value for tb_task_arrangement.ARRANGEMENT_ID
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setArrangementId(String arrangementId) {
        this.arrangementId = arrangementId == null ? null : arrangementId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.SHIFT
     *
     * @return the value of tb_task_arrangement.SHIFT
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getShift() {
        return shift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.SHIFT
     *
     * @param shift the value for tb_task_arrangement.SHIFT
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setShift(String shift) {
        this.shift = shift == null ? null : shift.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.EMPLOYEE_CODE
     *
     * @return the value of tb_task_arrangement.EMPLOYEE_CODE
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.EMPLOYEE_CODE
     *
     * @param employeeCode the value for tb_task_arrangement.EMPLOYEE_CODE
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.EMPLOYEE_NAME
     *
     * @return the value of tb_task_arrangement.EMPLOYEE_NAME
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.EMPLOYEE_NAME
     *
     * @param employeeName the value for tb_task_arrangement.EMPLOYEE_NAME
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.EMPLOYEE_TEL
     *
     * @return the value of tb_task_arrangement.EMPLOYEE_TEL
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getEmployeeTel() {
        return employeeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.EMPLOYEE_TEL
     *
     * @param employeeTel the value for tb_task_arrangement.EMPLOYEE_TEL
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setEmployeeTel(String employeeTel) {
        this.employeeTel = employeeTel == null ? null : employeeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.POSITION_CODE
     *
     * @return the value of tb_task_arrangement.POSITION_CODE
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getPositionCode() {
        return positionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.POSITION_CODE
     *
     * @param positionCode the value for tb_task_arrangement.POSITION_CODE
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setPositionCode(String positionCode) {
        this.positionCode = positionCode == null ? null : positionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.POSITION_NAME
     *
     * @return the value of tb_task_arrangement.POSITION_NAME
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.POSITION_NAME
     *
     * @param positionName the value for tb_task_arrangement.POSITION_NAME
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.MONTH
     *
     * @return the value of tb_task_arrangement.MONTH
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.MONTH
     *
     * @param month the value for tb_task_arrangement.MONTH
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DELETE_FLAG
     *
     * @return the value of tb_task_arrangement.DELETE_FLAG
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DELETE_FLAG
     *
     * @param deleteFlag the value for tb_task_arrangement.DELETE_FLAG
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_1
     *
     * @return the value of tb_task_arrangement.DAY_1
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay1() {
        return day1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_1
     *
     * @param day1 the value for tb_task_arrangement.DAY_1
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay1(String day1) {
        this.day1 = day1 == null ? null : day1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_2
     *
     * @return the value of tb_task_arrangement.DAY_2
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay2() {
        return day2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_2
     *
     * @param day2 the value for tb_task_arrangement.DAY_2
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay2(String day2) {
        this.day2 = day2 == null ? null : day2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_3
     *
     * @return the value of tb_task_arrangement.DAY_3
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay3() {
        return day3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_3
     *
     * @param day3 the value for tb_task_arrangement.DAY_3
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay3(String day3) {
        this.day3 = day3 == null ? null : day3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_4
     *
     * @return the value of tb_task_arrangement.DAY_4
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay4() {
        return day4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_4
     *
     * @param day4 the value for tb_task_arrangement.DAY_4
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay4(String day4) {
        this.day4 = day4 == null ? null : day4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_5
     *
     * @return the value of tb_task_arrangement.DAY_5
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay5() {
        return day5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_5
     *
     * @param day5 the value for tb_task_arrangement.DAY_5
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay5(String day5) {
        this.day5 = day5 == null ? null : day5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_6
     *
     * @return the value of tb_task_arrangement.DAY_6
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay6() {
        return day6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_6
     *
     * @param day6 the value for tb_task_arrangement.DAY_6
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay6(String day6) {
        this.day6 = day6 == null ? null : day6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_7
     *
     * @return the value of tb_task_arrangement.DAY_7
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay7() {
        return day7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_7
     *
     * @param day7 the value for tb_task_arrangement.DAY_7
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay7(String day7) {
        this.day7 = day7 == null ? null : day7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_8
     *
     * @return the value of tb_task_arrangement.DAY_8
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay8() {
        return day8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_8
     *
     * @param day8 the value for tb_task_arrangement.DAY_8
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay8(String day8) {
        this.day8 = day8 == null ? null : day8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_9
     *
     * @return the value of tb_task_arrangement.DAY_9
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay9() {
        return day9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_9
     *
     * @param day9 the value for tb_task_arrangement.DAY_9
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay9(String day9) {
        this.day9 = day9 == null ? null : day9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_10
     *
     * @return the value of tb_task_arrangement.DAY_10
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay10() {
        return day10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_10
     *
     * @param day10 the value for tb_task_arrangement.DAY_10
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay10(String day10) {
        this.day10 = day10 == null ? null : day10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_11
     *
     * @return the value of tb_task_arrangement.DAY_11
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay11() {
        return day11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_11
     *
     * @param day11 the value for tb_task_arrangement.DAY_11
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay11(String day11) {
        this.day11 = day11 == null ? null : day11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_12
     *
     * @return the value of tb_task_arrangement.DAY_12
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay12() {
        return day12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_12
     *
     * @param day12 the value for tb_task_arrangement.DAY_12
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay12(String day12) {
        this.day12 = day12 == null ? null : day12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_13
     *
     * @return the value of tb_task_arrangement.DAY_13
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay13() {
        return day13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_13
     *
     * @param day13 the value for tb_task_arrangement.DAY_13
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay13(String day13) {
        this.day13 = day13 == null ? null : day13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_14
     *
     * @return the value of tb_task_arrangement.DAY_14
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay14() {
        return day14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_14
     *
     * @param day14 the value for tb_task_arrangement.DAY_14
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay14(String day14) {
        this.day14 = day14 == null ? null : day14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_15
     *
     * @return the value of tb_task_arrangement.DAY_15
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay15() {
        return day15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_15
     *
     * @param day15 the value for tb_task_arrangement.DAY_15
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay15(String day15) {
        this.day15 = day15 == null ? null : day15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_16
     *
     * @return the value of tb_task_arrangement.DAY_16
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay16() {
        return day16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_16
     *
     * @param day16 the value for tb_task_arrangement.DAY_16
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay16(String day16) {
        this.day16 = day16 == null ? null : day16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_17
     *
     * @return the value of tb_task_arrangement.DAY_17
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay17() {
        return day17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_17
     *
     * @param day17 the value for tb_task_arrangement.DAY_17
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay17(String day17) {
        this.day17 = day17 == null ? null : day17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_18
     *
     * @return the value of tb_task_arrangement.DAY_18
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay18() {
        return day18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_18
     *
     * @param day18 the value for tb_task_arrangement.DAY_18
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay18(String day18) {
        this.day18 = day18 == null ? null : day18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_19
     *
     * @return the value of tb_task_arrangement.DAY_19
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay19() {
        return day19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_19
     *
     * @param day19 the value for tb_task_arrangement.DAY_19
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay19(String day19) {
        this.day19 = day19 == null ? null : day19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_20
     *
     * @return the value of tb_task_arrangement.DAY_20
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay20() {
        return day20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_20
     *
     * @param day20 the value for tb_task_arrangement.DAY_20
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay20(String day20) {
        this.day20 = day20 == null ? null : day20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_21
     *
     * @return the value of tb_task_arrangement.DAY_21
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay21() {
        return day21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_21
     *
     * @param day21 the value for tb_task_arrangement.DAY_21
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay21(String day21) {
        this.day21 = day21 == null ? null : day21.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_22
     *
     * @return the value of tb_task_arrangement.DAY_22
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay22() {
        return day22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_22
     *
     * @param day22 the value for tb_task_arrangement.DAY_22
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay22(String day22) {
        this.day22 = day22 == null ? null : day22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_23
     *
     * @return the value of tb_task_arrangement.DAY_23
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay23() {
        return day23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_23
     *
     * @param day23 the value for tb_task_arrangement.DAY_23
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay23(String day23) {
        this.day23 = day23 == null ? null : day23.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_24
     *
     * @return the value of tb_task_arrangement.DAY_24
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay24() {
        return day24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_24
     *
     * @param day24 the value for tb_task_arrangement.DAY_24
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay24(String day24) {
        this.day24 = day24 == null ? null : day24.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_25
     *
     * @return the value of tb_task_arrangement.DAY_25
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay25() {
        return day25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_25
     *
     * @param day25 the value for tb_task_arrangement.DAY_25
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay25(String day25) {
        this.day25 = day25 == null ? null : day25.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_26
     *
     * @return the value of tb_task_arrangement.DAY_26
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay26() {
        return day26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_26
     *
     * @param day26 the value for tb_task_arrangement.DAY_26
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay26(String day26) {
        this.day26 = day26 == null ? null : day26.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_27
     *
     * @return the value of tb_task_arrangement.DAY_27
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay27() {
        return day27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_27
     *
     * @param day27 the value for tb_task_arrangement.DAY_27
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay27(String day27) {
        this.day27 = day27 == null ? null : day27.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_28
     *
     * @return the value of tb_task_arrangement.DAY_28
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay28() {
        return day28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_28
     *
     * @param day28 the value for tb_task_arrangement.DAY_28
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay28(String day28) {
        this.day28 = day28 == null ? null : day28.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_29
     *
     * @return the value of tb_task_arrangement.DAY_29
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay29() {
        return day29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_29
     *
     * @param day29 the value for tb_task_arrangement.DAY_29
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay29(String day29) {
        this.day29 = day29 == null ? null : day29.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_30
     *
     * @return the value of tb_task_arrangement.DAY_30
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay30() {
        return day30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_30
     *
     * @param day30 the value for tb_task_arrangement.DAY_30
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay30(String day30) {
        this.day30 = day30 == null ? null : day30.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.DAY_31
     *
     * @return the value of tb_task_arrangement.DAY_31
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getDay31() {
        return day31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.DAY_31
     *
     * @param day31 the value for tb_task_arrangement.DAY_31
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setDay31(String day31) {
        this.day31 = day31 == null ? null : day31.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.REMARK1
     *
     * @return the value of tb_task_arrangement.REMARK1
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.REMARK1
     *
     * @param remark1 the value for tb_task_arrangement.REMARK1
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.REMARK2
     *
     * @return the value of tb_task_arrangement.REMARK2
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.REMARK2
     *
     * @param remark2 the value for tb_task_arrangement.REMARK2
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.REMARK3
     *
     * @return the value of tb_task_arrangement.REMARK3
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.REMARK3
     *
     * @param remark3 the value for tb_task_arrangement.REMARK3
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.CREATE_EMP
     *
     * @return the value of tb_task_arrangement.CREATE_EMP
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.CREATE_EMP
     *
     * @param createEmp the value for tb_task_arrangement.CREATE_EMP
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.CREATE_DATE
     *
     * @return the value of tb_task_arrangement.CREATE_DATE
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.CREATE_DATE
     *
     * @param createDate the value for tb_task_arrangement.CREATE_DATE
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.UPDATE_DATE
     *
     * @return the value of tb_task_arrangement.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.UPDATE_DATE
     *
     * @param updateDate the value for tb_task_arrangement.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.UPDATE_EMP
     *
     * @return the value of tb_task_arrangement.UPDATE_EMP
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.UPDATE_EMP
     *
     * @param updateEmp the value for tb_task_arrangement.UPDATE_EMP
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrangement.VERSION
     *
     * @return the value of tb_task_arrangement.VERSION
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrangement.VERSION
     *
     * @param version the value for tb_task_arrangement.VERSION
     *
     * @mbggenerated Wed Oct 17 09:35:30 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}