package com.qcap.cac.entity;

import java.util.Date;

public class TbTaskDelay {
    /**
    *   主键
     */
    private String taskDelayId;

    /**
    *   任务编号
     */
    private String taskCode;

    /**
    *   延迟天数
     */
    private String delayDays;

    /**
    *   操作时间
     */
    private Date operationDate;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.TASK_DELAY_ID
     *
     * @return the value of tb_task_delay.TASK_DELAY_ID
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public String getTaskDelayId() {
        return taskDelayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.TASK_DELAY_ID
     *
     * @param taskDelayId the value for tb_task_delay.TASK_DELAY_ID
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setTaskDelayId(String taskDelayId) {
        this.taskDelayId = taskDelayId == null ? null : taskDelayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.TASK_CODE
     *
     * @return the value of tb_task_delay.TASK_CODE
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.TASK_CODE
     *
     * @param taskCode the value for tb_task_delay.TASK_CODE
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.DELAY_DAYS
     *
     * @return the value of tb_task_delay.DELAY_DAYS
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public String getDelayDays() {
        return delayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.DELAY_DAYS
     *
     * @param delayDays the value for tb_task_delay.DELAY_DAYS
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setDelayDays(String delayDays) {
        this.delayDays = delayDays == null ? null : delayDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.OPERATION_DATE
     *
     * @return the value of tb_task_delay.OPERATION_DATE
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.OPERATION_DATE
     *
     * @param operationDate the value for tb_task_delay.OPERATION_DATE
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.REMARK1
     *
     * @return the value of tb_task_delay.REMARK1
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.REMARK1
     *
     * @param remark1 the value for tb_task_delay.REMARK1
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.REMARK2
     *
     * @return the value of tb_task_delay.REMARK2
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.REMARK2
     *
     * @param remark2 the value for tb_task_delay.REMARK2
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.REMARK3
     *
     * @return the value of tb_task_delay.REMARK3
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.REMARK3
     *
     * @param remark3 the value for tb_task_delay.REMARK3
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.CREATE_EMP
     *
     * @return the value of tb_task_delay.CREATE_EMP
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.CREATE_EMP
     *
     * @param createEmp the value for tb_task_delay.CREATE_EMP
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.CREATE_DATE
     *
     * @return the value of tb_task_delay.CREATE_DATE
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.CREATE_DATE
     *
     * @param createDate the value for tb_task_delay.CREATE_DATE
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.UPDATE_DATE
     *
     * @return the value of tb_task_delay.UPDATE_DATE
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.UPDATE_DATE
     *
     * @param updateDate the value for tb_task_delay.UPDATE_DATE
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.UPDATE_EMP
     *
     * @return the value of tb_task_delay.UPDATE_EMP
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.UPDATE_EMP
     *
     * @param updateEmp the value for tb_task_delay.UPDATE_EMP
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_delay.VERSION
     *
     * @return the value of tb_task_delay.VERSION
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_delay.VERSION
     *
     * @param version the value for tb_task_delay.VERSION
     *
     * @mbggenerated Tue Nov 06 14:42:57 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}