package com.qcap.cac.entity;

import java.io.Serializable;
import java.util.Date;

public class TbTaskArrangeShift implements Serializable {

    /**
    *   主键
     */
    private String arrangeShiftId;

    /**
    *   班次
     */
    private String shift;

    /**
    *   岗位编号
     */
    private String positionCode;

    /**
    *   岗位名称
     */
    private String positionName;

    /**
    *   员工编号
     */
    private String employeeCode;

    /**
    *   员工姓名
     */
    private String employeeName;

    /**
    *   调班日期
     */
    private Date changeDate;

    /**
    *   顶班人工号
     */
    private String extraEmployeeCode;

    /**
    *   顶班人名称
     */
    private String extraEmployeeName;

    /**
    *   调班开始时间
     */
    private Date startTime;

    /**
    *   调班结束时间
     */
    private Date endTime;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.ARRANGE_SHIFT_ID
     *
     * @return the value of tb_task_arrange_shift.ARRANGE_SHIFT_ID
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getArrangeShiftId() {
        return arrangeShiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.ARRANGE_SHIFT_ID
     *
     * @param arrangeShiftId the value for tb_task_arrange_shift.ARRANGE_SHIFT_ID
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setArrangeShiftId(String arrangeShiftId) {
        this.arrangeShiftId = arrangeShiftId == null ? null : arrangeShiftId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.SHIFT
     *
     * @return the value of tb_task_arrange_shift.SHIFT
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getShift() {
        return shift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.SHIFT
     *
     * @param shift the value for tb_task_arrange_shift.SHIFT
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setShift(String shift) {
        this.shift = shift == null ? null : shift.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.POSITION_CODE
     *
     * @return the value of tb_task_arrange_shift.POSITION_CODE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getPositionCode() {
        return positionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.POSITION_CODE
     *
     * @param positionCode the value for tb_task_arrange_shift.POSITION_CODE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setPositionCode(String positionCode) {
        this.positionCode = positionCode == null ? null : positionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.POSITION_NAME
     *
     * @return the value of tb_task_arrange_shift.POSITION_NAME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.POSITION_NAME
     *
     * @param positionName the value for tb_task_arrange_shift.POSITION_NAME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.EMPLOYEE_CODE
     *
     * @return the value of tb_task_arrange_shift.EMPLOYEE_CODE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.EMPLOYEE_CODE
     *
     * @param employeeCode the value for tb_task_arrange_shift.EMPLOYEE_CODE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.EMPLOYEE_NAME
     *
     * @return the value of tb_task_arrange_shift.EMPLOYEE_NAME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.EMPLOYEE_NAME
     *
     * @param employeeName the value for tb_task_arrange_shift.EMPLOYEE_NAME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.CHANGE_DATE
     *
     * @return the value of tb_task_arrange_shift.CHANGE_DATE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public Date getChangeDate() {
        return changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.CHANGE_DATE
     *
     * @param changeDate the value for tb_task_arrange_shift.CHANGE_DATE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.EXTRA_EMPLOYEE_CODE
     *
     * @return the value of tb_task_arrange_shift.EXTRA_EMPLOYEE_CODE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getExtraEmployeeCode() {
        return extraEmployeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.EXTRA_EMPLOYEE_CODE
     *
     * @param extraEmployeeCode the value for tb_task_arrange_shift.EXTRA_EMPLOYEE_CODE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setExtraEmployeeCode(String extraEmployeeCode) {
        this.extraEmployeeCode = extraEmployeeCode == null ? null : extraEmployeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.EXTRA_EMPLOYEE_NAME
     *
     * @return the value of tb_task_arrange_shift.EXTRA_EMPLOYEE_NAME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getExtraEmployeeName() {
        return extraEmployeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.EXTRA_EMPLOYEE_NAME
     *
     * @param extraEmployeeName the value for tb_task_arrange_shift.EXTRA_EMPLOYEE_NAME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setExtraEmployeeName(String extraEmployeeName) {
        this.extraEmployeeName = extraEmployeeName == null ? null : extraEmployeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.START_TIME
     *
     * @return the value of tb_task_arrange_shift.START_TIME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.START_TIME
     *
     * @param startTime the value for tb_task_arrange_shift.START_TIME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.END_TIME
     *
     * @return the value of tb_task_arrange_shift.END_TIME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.END_TIME
     *
     * @param endTime the value for tb_task_arrange_shift.END_TIME
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.REMARK1
     *
     * @return the value of tb_task_arrange_shift.REMARK1
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.REMARK1
     *
     * @param remark1 the value for tb_task_arrange_shift.REMARK1
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.REMARK2
     *
     * @return the value of tb_task_arrange_shift.REMARK2
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.REMARK2
     *
     * @param remark2 the value for tb_task_arrange_shift.REMARK2
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.REMARK3
     *
     * @return the value of tb_task_arrange_shift.REMARK3
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.REMARK3
     *
     * @param remark3 the value for tb_task_arrange_shift.REMARK3
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.CREATE_EMP
     *
     * @return the value of tb_task_arrange_shift.CREATE_EMP
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.CREATE_EMP
     *
     * @param createEmp the value for tb_task_arrange_shift.CREATE_EMP
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.CREATE_DATE
     *
     * @return the value of tb_task_arrange_shift.CREATE_DATE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.CREATE_DATE
     *
     * @param createDate the value for tb_task_arrange_shift.CREATE_DATE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.UPDATE_DATE
     *
     * @return the value of tb_task_arrange_shift.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.UPDATE_DATE
     *
     * @param updateDate the value for tb_task_arrange_shift.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.UPDATE_EMP
     *
     * @return the value of tb_task_arrange_shift.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.UPDATE_EMP
     *
     * @param updateEmp the value for tb_task_arrange_shift.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task_arrange_shift.VERSION
     *
     * @return the value of tb_task_arrange_shift.VERSION
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task_arrange_shift.VERSION
     *
     * @param version the value for tb_task_arrange_shift.VERSION
     *
     * @mbggenerated Tue Oct 30 19:52:46 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}