package com.qcap.cac.entity;

import java.util.Date;

public class TbWarehousePurchase {
    /**
     *   采购主键ID
     */
    private String warehousePurchaseId;

    /**
     *   采购类别
     */
    private String buyType;

    /**
     *   采购编号
     */
    private String buyNo;

    /**
     *   物品类别
     */
    private String goodsType;

    /**
     *   物品编码
     */
    private String goodsNo;

    /**
     *   物品名称
     */
    private String goodsName;

    /**
     *   SUPPLIER_NAME_第一阶段保持一致
     */
    private String supplierNo;

    /**
     *   供应商名称
     */
    private String supplierName;

    /**
     *   采购数量
     */
    private Integer buyNum;

    /**
     *   采购单位(和入库单位保持一致)
     */
    private String entryUnit;

    /**
     *   申请采购日期
     */
    private Date buyTime;

    /**
     *   备注
     */
    private String remark;

    /**
     *   新增人
     */
    private String createEmp;

    /**
     *   新增时间
     */
    private Date createDate;

    /**
     *   修改人
     */
    private String updateEmp;

    /**
     *   修改时间
     */
    private Date updateDate;

    /**
     *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.WAREHOUSE_PURCHASE_ID
     *
     * @return the value of tb_warehouse_purchase.WAREHOUSE_PURCHASE_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehousePurchaseId() {
        return warehousePurchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.WAREHOUSE_PURCHASE_ID
     *
     * @param warehousePurchaseId the value for tb_warehouse_purchase.WAREHOUSE_PURCHASE_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehousePurchaseId(String warehousePurchaseId) {
        this.warehousePurchaseId = warehousePurchaseId == null ? null : warehousePurchaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.BUY_TYPE
     *
     * @return the value of tb_warehouse_purchase.BUY_TYPE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getBuyType() {
        return buyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.BUY_TYPE
     *
     * @param buyType the value for tb_warehouse_purchase.BUY_TYPE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setBuyType(String buyType) {
        this.buyType = buyType == null ? null : buyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.BUY_NO
     *
     * @return the value of tb_warehouse_purchase.BUY_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getBuyNo() {
        return buyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.BUY_NO
     *
     * @param buyNo the value for tb_warehouse_purchase.BUY_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setBuyNo(String buyNo) {
        this.buyNo = buyNo == null ? null : buyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.GOODS_TYPE
     *
     * @return the value of tb_warehouse_purchase.GOODS_TYPE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.GOODS_TYPE
     *
     * @param goodsType the value for tb_warehouse_purchase.GOODS_TYPE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.GOODS_NO
     *
     * @return the value of tb_warehouse_purchase.GOODS_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getGoodsNo() {
        return goodsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.GOODS_NO
     *
     * @param goodsNo the value for tb_warehouse_purchase.GOODS_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setGoodsNo(String goodsNo) {
        this.goodsNo = goodsNo == null ? null : goodsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.GOODS_NAME
     *
     * @return the value of tb_warehouse_purchase.GOODS_NAME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.GOODS_NAME
     *
     * @param goodsName the value for tb_warehouse_purchase.GOODS_NAME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.SUPPLIER_NO
     *
     * @return the value of tb_warehouse_purchase.SUPPLIER_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getSupplierNo() {
        return supplierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.SUPPLIER_NO
     *
     * @param supplierNo the value for tb_warehouse_purchase.SUPPLIER_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setSupplierNo(String supplierNo) {
        this.supplierNo = supplierNo == null ? null : supplierNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.SUPPLIER_NAME
     *
     * @return the value of tb_warehouse_purchase.SUPPLIER_NAME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.SUPPLIER_NAME
     *
     * @param supplierName the value for tb_warehouse_purchase.SUPPLIER_NAME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.BUY_NUM
     *
     * @return the value of tb_warehouse_purchase.BUY_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Integer getBuyNum() {
        return buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.BUY_NUM
     *
     * @param buyNum the value for tb_warehouse_purchase.BUY_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setBuyNum(Integer buyNum) {
        this.buyNum = buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.ENTRY_UNIT
     *
     * @return the value of tb_warehouse_purchase.ENTRY_UNIT
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getEntryUnit() {
        return entryUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.ENTRY_UNIT
     *
     * @param entryUnit the value for tb_warehouse_purchase.ENTRY_UNIT
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setEntryUnit(String entryUnit) {
        this.entryUnit = entryUnit == null ? null : entryUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.BUY_TIME_
     *
     * @return the value of tb_warehouse_purchase.BUY_TIME_
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.BUY_TIME_
     *
     * @param buyTime the value for tb_warehouse_purchase.BUY_TIME_
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.REMARK
     *
     * @return the value of tb_warehouse_purchase.REMARK
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.REMARK
     *
     * @param remark the value for tb_warehouse_purchase.REMARK
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.CREATE_EMP
     *
     * @return the value of tb_warehouse_purchase.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.CREATE_EMP
     *
     * @param createEmp the value for tb_warehouse_purchase.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.CREATE_DATE
     *
     * @return the value of tb_warehouse_purchase.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.CREATE_DATE
     *
     * @param createDate the value for tb_warehouse_purchase.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.UPDATE_EMP
     *
     * @return the value of tb_warehouse_purchase.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.UPDATE_EMP
     *
     * @param updateEmp the value for tb_warehouse_purchase.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.UPDATE_DATE
     *
     * @return the value of tb_warehouse_purchase.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.UPDATE_DATE
     *
     * @param updateDate the value for tb_warehouse_purchase.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_purchase.VERSION
     *
     * @return the value of tb_warehouse_purchase.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_purchase.VERSION
     *
     * @param version the value for tb_warehouse_purchase.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}