package com.qcap.cac.entity;

import java.util.Date;

public class TbWarehouseStorage {
    /**
     *   主键
     */
    private String warehouseStorageId;

    /**
     *   库位主键
     */
    private String warehousePositionId;

    /**
     *   物品库存主键
     */
    private String warehouseStockId;

    /**
     *   新增人
     */
    private String createEmp;

    /**
     *   新增时间
     */
    private Date createDate;

    /**
     *   修改人
     */
    private String updateEmp;

    /**
     *   修改时间
     */
    private Date updateDate;

    /**
     *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_storage.WAREHOUSE_STORAGE_ID
     *
     * @return the value of tb_warehouse_storage.WAREHOUSE_STORAGE_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehouseStorageId() {
        return warehouseStorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_storage.WAREHOUSE_STORAGE_ID
     *
     * @param warehouseStorageId the value for tb_warehouse_storage.WAREHOUSE_STORAGE_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehouseStorageId(String warehouseStorageId) {
        this.warehouseStorageId = warehouseStorageId == null ? null : warehouseStorageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_storage.WAREHOUSE_POSITION_ID
     *
     * @return the value of tb_warehouse_storage.WAREHOUSE_POSITION_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehousePositionId() {
        return warehousePositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_storage.WAREHOUSE_POSITION_ID
     *
     * @param warehousePositionId the value for tb_warehouse_storage.WAREHOUSE_POSITION_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehousePositionId(String warehousePositionId) {
        this.warehousePositionId = warehousePositionId == null ? null : warehousePositionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_storage.WAREHOUSE_STOCK_ID
     *
     * @return the value of tb_warehouse_storage.WAREHOUSE_STOCK_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehouseStockId() {
        return warehouseStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_storage.WAREHOUSE_STOCK_ID
     *
     * @param warehouseStockId the value for tb_warehouse_storage.WAREHOUSE_STOCK_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehouseStockId(String warehouseStockId) {
        this.warehouseStockId = warehouseStockId == null ? null : warehouseStockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_storage.CREATE_EMP
     *
     * @return the value of tb_warehouse_storage.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_storage.CREATE_EMP
     *
     * @param createEmp the value for tb_warehouse_storage.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_storage.CREATE_DATE
     *
     * @return the value of tb_warehouse_storage.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_storage.CREATE_DATE
     *
     * @param createDate the value for tb_warehouse_storage.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_storage.UPDATE_EMP
     *
     * @return the value of tb_warehouse_storage.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_storage.UPDATE_EMP
     *
     * @param updateEmp the value for tb_warehouse_storage.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_storage.UPDATE_DATE
     *
     * @return the value of tb_warehouse_storage.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_storage.UPDATE_DATE
     *
     * @param updateDate the value for tb_warehouse_storage.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_storage.VERSION
     *
     * @return the value of tb_warehouse_storage.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_storage.VERSION
     *
     * @param version the value for tb_warehouse_storage.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}