package com.qcap.cac.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TbWarehouseEntry {
    /**
     *   入库主键
     */
    private String warehouseEntryId;

    /**
     *   储藏室
     */
    private String storeroomId;

    /**
     *   储藏室名称
     */
    private String storeroom;

    /**
     *   生成规则（P +YYYYMMDDHHMMSS）
     */
    private String entryBatchNo;

    /**
     *   物品库存主键
     */
    private String warehouseStockId;

    /**
     *   数量
     */
    private Integer entryNum;

    /**
     *   单位名称
     */
    private String entryUnit;

    /**
     *   总数量
     */
    private BigDecimal sumNum;

    /**
     *   最小单位
     */
    private String minUnit;

    /**
     *   入库时间
     */
    private Date entryTime;

    /**
     *   删除标志(Y删除N未删除)
     */
    private String deleteFlag;

    /**
     *   新增人
     */
    private String createEmp;

    /**
     *   新增时间
     */
    private Date createDate;

    /**
     *   修改人
     */
    private String updateEmp;

    /**
     *   修改时间
     */
    private Date updateDate;

    /**
     *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.WAREHOUSE_ENTRY_ID
     *
     * @return the value of tb_warehouse_entry.WAREHOUSE_ENTRY_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehouseEntryId() {
        return warehouseEntryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.WAREHOUSE_ENTRY_ID
     *
     * @param warehouseEntryId the value for tb_warehouse_entry.WAREHOUSE_ENTRY_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehouseEntryId(String warehouseEntryId) {
        this.warehouseEntryId = warehouseEntryId == null ? null : warehouseEntryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.STOREROOM_ID
     *
     * @return the value of tb_warehouse_entry.STOREROOM_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getStoreroomId() {
        return storeroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.STOREROOM_ID
     *
     * @param storeroomId the value for tb_warehouse_entry.STOREROOM_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setStoreroomId(String storeroomId) {
        this.storeroomId = storeroomId == null ? null : storeroomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.STOREROOM
     *
     * @return the value of tb_warehouse_entry.STOREROOM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getStoreroom() {
        return storeroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.STOREROOM
     *
     * @param storeroom the value for tb_warehouse_entry.STOREROOM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setStoreroom(String storeroom) {
        this.storeroom = storeroom == null ? null : storeroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.ENTRY_BATCH_NO
     *
     * @return the value of tb_warehouse_entry.ENTRY_BATCH_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getEntryBatchNo() {
        return entryBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.ENTRY_BATCH_NO
     *
     * @param entryBatchNo the value for tb_warehouse_entry.ENTRY_BATCH_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setEntryBatchNo(String entryBatchNo) {
        this.entryBatchNo = entryBatchNo == null ? null : entryBatchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.WAREHOUSE_STOCK_ID
     *
     * @return the value of tb_warehouse_entry.WAREHOUSE_STOCK_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehouseStockId() {
        return warehouseStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.WAREHOUSE_STOCK_ID
     *
     * @param warehouseStockId the value for tb_warehouse_entry.WAREHOUSE_STOCK_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehouseStockId(String warehouseStockId) {
        this.warehouseStockId = warehouseStockId == null ? null : warehouseStockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.ENTRY_NUM
     *
     * @return the value of tb_warehouse_entry.ENTRY_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Integer getEntryNum() {
        return entryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.ENTRY_NUM
     *
     * @param entryNum the value for tb_warehouse_entry.ENTRY_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setEntryNum(Integer entryNum) {
        this.entryNum = entryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.ENTRY_UNIT_
     *
     * @return the value of tb_warehouse_entry.ENTRY_UNIT_
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getEntryUnit() {
        return entryUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.ENTRY_UNIT_
     *
     * @param entryUnit the value for tb_warehouse_entry.ENTRY_UNIT_
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setEntryUnit(String entryUnit) {
        this.entryUnit = entryUnit == null ? null : entryUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.SUM_NUM
     *
     * @return the value of tb_warehouse_entry.SUM_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public BigDecimal getSumNum() {
        return sumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.SUM_NUM
     *
     * @param sumNum the value for tb_warehouse_entry.SUM_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setSumNum(BigDecimal sumNum) {
        this.sumNum = sumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.MIN_UNIT
     *
     * @return the value of tb_warehouse_entry.MIN_UNIT
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getMinUnit() {
        return minUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.MIN_UNIT
     *
     * @param minUnit the value for tb_warehouse_entry.MIN_UNIT
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setMinUnit(String minUnit) {
        this.minUnit = minUnit == null ? null : minUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.ENTRY_TIME
     *
     * @return the value of tb_warehouse_entry.ENTRY_TIME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.ENTRY_TIME
     *
     * @param entryTime the value for tb_warehouse_entry.ENTRY_TIME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.DELETE_FLAG
     *
     * @return the value of tb_warehouse_entry.DELETE_FLAG
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.DELETE_FLAG
     *
     * @param deleteFlag the value for tb_warehouse_entry.DELETE_FLAG
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.CREATE_EMP
     *
     * @return the value of tb_warehouse_entry.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.CREATE_EMP
     *
     * @param createEmp the value for tb_warehouse_entry.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.CREATE_DATE
     *
     * @return the value of tb_warehouse_entry.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.CREATE_DATE
     *
     * @param createDate the value for tb_warehouse_entry.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.UPDATE_EMP
     *
     * @return the value of tb_warehouse_entry.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.UPDATE_EMP
     *
     * @param updateEmp the value for tb_warehouse_entry.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.UPDATE_DATE
     *
     * @return the value of tb_warehouse_entry.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.UPDATE_DATE
     *
     * @param updateDate the value for tb_warehouse_entry.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_entry.VERSION
     *
     * @return the value of tb_warehouse_entry.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_entry.VERSION
     *
     * @param version the value for tb_warehouse_entry.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}