package com.qcap.cac.entity;

import java.util.Date;

public class TbWarehouseStockLog {
    /**
     *   主键ID
     */
    private String warehouseStockLogId;

    /**
     *   物品库存主键ID
     */
    private String warehouseStockId;

    /**
     *   物品类别
     */
    private String goodsType;

    /**
     *   物品编码
     */
    private String goodsNo;

    /**
     *   物品名称
     */
    private String goodsName;

    /**
     *   操作日志
     */
    private String logOperation;

    /**
     *   备注
     */
    private String remark;

    /**
     *   新增人
     */
    private String createEmp;

    /**
     *   新增时间
     */
    private Date createDate;

    /**
     *   修改人
     */
    private String updateEmp;

    /**
     *   修改时间
     */
    private Date updateDate;

    /**
     *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.WAREHOUSE_STOCK_LOG_ID
     *
     * @return the value of tb_warehouse_stock_log.WAREHOUSE_STOCK_LOG_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehouseStockLogId() {
        return warehouseStockLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.WAREHOUSE_STOCK_LOG_ID
     *
     * @param warehouseStockLogId the value for tb_warehouse_stock_log.WAREHOUSE_STOCK_LOG_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehouseStockLogId(String warehouseStockLogId) {
        this.warehouseStockLogId = warehouseStockLogId == null ? null : warehouseStockLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.WAREHOUSE_STOCK_ID
     *
     * @return the value of tb_warehouse_stock_log.WAREHOUSE_STOCK_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehouseStockId() {
        return warehouseStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.WAREHOUSE_STOCK_ID
     *
     * @param warehouseStockId the value for tb_warehouse_stock_log.WAREHOUSE_STOCK_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehouseStockId(String warehouseStockId) {
        this.warehouseStockId = warehouseStockId == null ? null : warehouseStockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.GOODS_TYPE
     *
     * @return the value of tb_warehouse_stock_log.GOODS_TYPE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.GOODS_TYPE
     *
     * @param goodsType the value for tb_warehouse_stock_log.GOODS_TYPE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.GOODS_NO
     *
     * @return the value of tb_warehouse_stock_log.GOODS_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getGoodsNo() {
        return goodsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.GOODS_NO
     *
     * @param goodsNo the value for tb_warehouse_stock_log.GOODS_NO
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setGoodsNo(String goodsNo) {
        this.goodsNo = goodsNo == null ? null : goodsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.GOODS_NAME
     *
     * @return the value of tb_warehouse_stock_log.GOODS_NAME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.GOODS_NAME
     *
     * @param goodsName the value for tb_warehouse_stock_log.GOODS_NAME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.LOG_OPERATION
     *
     * @return the value of tb_warehouse_stock_log.LOG_OPERATION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getLogOperation() {
        return logOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.LOG_OPERATION
     *
     * @param logOperation the value for tb_warehouse_stock_log.LOG_OPERATION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setLogOperation(String logOperation) {
        this.logOperation = logOperation == null ? null : logOperation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.REMARK
     *
     * @return the value of tb_warehouse_stock_log.REMARK
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.REMARK
     *
     * @param remark the value for tb_warehouse_stock_log.REMARK
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.CREATE_EMP
     *
     * @return the value of tb_warehouse_stock_log.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.CREATE_EMP
     *
     * @param createEmp the value for tb_warehouse_stock_log.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.CREATE_DATE
     *
     * @return the value of tb_warehouse_stock_log.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.CREATE_DATE
     *
     * @param createDate the value for tb_warehouse_stock_log.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.UPDATE_EMP
     *
     * @return the value of tb_warehouse_stock_log.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.UPDATE_EMP
     *
     * @param updateEmp the value for tb_warehouse_stock_log.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.UPDATE_DATE
     *
     * @return the value of tb_warehouse_stock_log.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.UPDATE_DATE
     *
     * @param updateDate the value for tb_warehouse_stock_log.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_stock_log.VERSION
     *
     * @return the value of tb_warehouse_stock_log.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_stock_log.VERSION
     *
     * @param version the value for tb_warehouse_stock_log.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}