package com.qcap.cac.entity;

import java.util.Date;

public class TbWarehouseReqdetail {
    /**
     *   领用申请明细主键
     */
    private String warehouseReqdetailId;

    /**
     *   领用申请主键
     */
    private String warehouseRequId;

    /**
     *   物品库存主键
     */
    private String warehouseStockId;

    /**
     *   领用区域
     */
    private String requLoc;

    /**
     *   领用区域名称
     */
    private String requLocName;

    /**
     *   申请数量
     */
    private Integer applyNum;

    /**
     *   实发数量
     */
    private Integer realNum;

    /**
     *   出库单位(与入库的最小单位保持一致)
     */
    private String minUnit;

    /**
     *   INIT已申请，COMMIT已提交，RECEIVE已领用
     */
    private String requStatus;

    /**
     *   领用说明
     */
    private String requRemark;

    /**
     *   新增人
     */
    private String createEmp;

    /**
     *   新增时间
     */
    private Date createDate;

    /**
     *   修改人
     */
    private String updateEmp;

    /**
     *   修改时间
     */
    private Date updateDate;

    /**
     *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.WAREHOUSE_REQDETAIL_ID
     *
     * @return the value of tb_warehouse_reqdetail.WAREHOUSE_REQDETAIL_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehouseReqdetailId() {
        return warehouseReqdetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.WAREHOUSE_REQDETAIL_ID
     *
     * @param warehouseReqdetailId the value for tb_warehouse_reqdetail.WAREHOUSE_REQDETAIL_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehouseReqdetailId(String warehouseReqdetailId) {
        this.warehouseReqdetailId = warehouseReqdetailId == null ? null : warehouseReqdetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.WAREHOUSE_REQU_ID
     *
     * @return the value of tb_warehouse_reqdetail.WAREHOUSE_REQU_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehouseRequId() {
        return warehouseRequId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.WAREHOUSE_REQU_ID
     *
     * @param warehouseRequId the value for tb_warehouse_reqdetail.WAREHOUSE_REQU_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehouseRequId(String warehouseRequId) {
        this.warehouseRequId = warehouseRequId == null ? null : warehouseRequId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.WAREHOUSE_STOCK_ID
     *
     * @return the value of tb_warehouse_reqdetail.WAREHOUSE_STOCK_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getWarehouseStockId() {
        return warehouseStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.WAREHOUSE_STOCK_ID
     *
     * @param warehouseStockId the value for tb_warehouse_reqdetail.WAREHOUSE_STOCK_ID
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setWarehouseStockId(String warehouseStockId) {
        this.warehouseStockId = warehouseStockId == null ? null : warehouseStockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.REQU_LOC
     *
     * @return the value of tb_warehouse_reqdetail.REQU_LOC
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getRequLoc() {
        return requLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.REQU_LOC
     *
     * @param requLoc the value for tb_warehouse_reqdetail.REQU_LOC
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setRequLoc(String requLoc) {
        this.requLoc = requLoc == null ? null : requLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.REQU_LOC_NAME
     *
     * @return the value of tb_warehouse_reqdetail.REQU_LOC_NAME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getRequLocName() {
        return requLocName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.REQU_LOC_NAME
     *
     * @param requLocName the value for tb_warehouse_reqdetail.REQU_LOC_NAME
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setRequLocName(String requLocName) {
        this.requLocName = requLocName == null ? null : requLocName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.APPLY_NUM
     *
     * @return the value of tb_warehouse_reqdetail.APPLY_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Integer getApplyNum() {
        return applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.APPLY_NUM
     *
     * @param applyNum the value for tb_warehouse_reqdetail.APPLY_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setApplyNum(Integer applyNum) {
        this.applyNum = applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.REAL_NUM
     *
     * @return the value of tb_warehouse_reqdetail.REAL_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Integer getRealNum() {
        return realNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.REAL_NUM
     *
     * @param realNum the value for tb_warehouse_reqdetail.REAL_NUM
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setRealNum(Integer realNum) {
        this.realNum = realNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.MIN_UNIT
     *
     * @return the value of tb_warehouse_reqdetail.MIN_UNIT
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getMinUnit() {
        return minUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.MIN_UNIT
     *
     * @param minUnit the value for tb_warehouse_reqdetail.MIN_UNIT
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setMinUnit(String minUnit) {
        this.minUnit = minUnit == null ? null : minUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.REQU_STATUS
     *
     * @return the value of tb_warehouse_reqdetail.REQU_STATUS
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getRequStatus() {
        return requStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.REQU_STATUS
     *
     * @param requStatus the value for tb_warehouse_reqdetail.REQU_STATUS
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setRequStatus(String requStatus) {
        this.requStatus = requStatus == null ? null : requStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.REQU_REMARK
     *
     * @return the value of tb_warehouse_reqdetail.REQU_REMARK
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getRequRemark() {
        return requRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.REQU_REMARK
     *
     * @param requRemark the value for tb_warehouse_reqdetail.REQU_REMARK
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setRequRemark(String requRemark) {
        this.requRemark = requRemark == null ? null : requRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.CREATE_EMP
     *
     * @return the value of tb_warehouse_reqdetail.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.CREATE_EMP
     *
     * @param createEmp the value for tb_warehouse_reqdetail.CREATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.CREATE_DATE
     *
     * @return the value of tb_warehouse_reqdetail.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.CREATE_DATE
     *
     * @param createDate the value for tb_warehouse_reqdetail.CREATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.UPDATE_EMP
     *
     * @return the value of tb_warehouse_reqdetail.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.UPDATE_EMP
     *
     * @param updateEmp the value for tb_warehouse_reqdetail.UPDATE_EMP
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.UPDATE_DATE
     *
     * @return the value of tb_warehouse_reqdetail.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.UPDATE_DATE
     *
     * @param updateDate the value for tb_warehouse_reqdetail.UPDATE_DATE
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse_reqdetail.VERSION
     *
     * @return the value of tb_warehouse_reqdetail.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse_reqdetail.VERSION
     *
     * @param version the value for tb_warehouse_reqdetail.VERSION
     *
     * @mbggenerated Tue Oct 09 19:52:33 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}