package com.qcap.cac.model;


import java.io.Serializable;
import java.util.Date;

public class Company implements Serializable{
	
    /**
	 * 
	 */
	private static final long serialVersionUID = -1271432910974991662L;

	/**
    *   主键
     */
    private String companyId;

    /**
    *   公司编号：三位流水号
     */
    private String companyCode;

    /**
    *   公司简称
     */
    private String compName;

    /**
    *   公司全称
     */
    private String fullName;

    /**
    *   公司品牌
     */
    private String compBrand;

    /**
    *   公司地址
     */
    private String address;

    /**
    *   邮政编码
     */
    private String mail;

    /**
    *   公司电话
     */
    private String compTel;

    /**
    *   传真号码
     */
    private String fax;

    /**
    *   公司网站
     */
    private String compWeb;

    /**
    *   电子邮箱
     */
    private String email;

    /**
    *   国税号
     */
    private String nationalTax;

    /**
    *   地税号
     */
    private String landTax;

    /**
    *   银行账号
     */
    private String bankAccount;

    /**
    *   开户银行
     */
    private String bank;

    /**
    *   默认是0
     */
    private String level;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.COMPANY_ID_
     *
     * @return the value of tb_sys_company.COMPANY_ID_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.COMPANY_ID_
     *
     * @param companyId the value for tb_sys_company.COMPANY_ID_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.COMPANY_CODE_
     *
     * @return the value of tb_sys_company.COMPANY_CODE_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.COMPANY_CODE_
     *
     * @param companyCode the value for tb_sys_company.COMPANY_CODE_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.COMP_NAME_
     *
     * @return the value of tb_sys_company.COMP_NAME_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getCompName() {
        return compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.COMP_NAME_
     *
     * @param compName the value for tb_sys_company.COMP_NAME_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.FULL_NAME_
     *
     * @return the value of tb_sys_company.FULL_NAME_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.FULL_NAME_
     *
     * @param fullName the value for tb_sys_company.FULL_NAME_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.COMP_BRAND_
     *
     * @return the value of tb_sys_company.COMP_BRAND_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getCompBrand() {
        return compBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.COMP_BRAND_
     *
     * @param compBrand the value for tb_sys_company.COMP_BRAND_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setCompBrand(String compBrand) {
        this.compBrand = compBrand == null ? null : compBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.ADDRESS_
     *
     * @return the value of tb_sys_company.ADDRESS_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.ADDRESS_
     *
     * @param address the value for tb_sys_company.ADDRESS_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.MAIL_
     *
     * @return the value of tb_sys_company.MAIL_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.MAIL_
     *
     * @param mail the value for tb_sys_company.MAIL_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.COMP_TEL_
     *
     * @return the value of tb_sys_company.COMP_TEL_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getCompTel() {
        return compTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.COMP_TEL_
     *
     * @param compTel the value for tb_sys_company.COMP_TEL_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setCompTel(String compTel) {
        this.compTel = compTel == null ? null : compTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.FAX_
     *
     * @return the value of tb_sys_company.FAX_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.FAX_
     *
     * @param fax the value for tb_sys_company.FAX_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.COMP_WEB_
     *
     * @return the value of tb_sys_company.COMP_WEB_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getCompWeb() {
        return compWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.COMP_WEB_
     *
     * @param compWeb the value for tb_sys_company.COMP_WEB_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setCompWeb(String compWeb) {
        this.compWeb = compWeb == null ? null : compWeb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.EMAIL_
     *
     * @return the value of tb_sys_company.EMAIL_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.EMAIL_
     *
     * @param email the value for tb_sys_company.EMAIL_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.NATIONAL_TAX_
     *
     * @return the value of tb_sys_company.NATIONAL_TAX_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getNationalTax() {
        return nationalTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.NATIONAL_TAX_
     *
     * @param nationalTax the value for tb_sys_company.NATIONAL_TAX_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setNationalTax(String nationalTax) {
        this.nationalTax = nationalTax == null ? null : nationalTax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.LAND_TAX_
     *
     * @return the value of tb_sys_company.LAND_TAX_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getLandTax() {
        return landTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.LAND_TAX_
     *
     * @param landTax the value for tb_sys_company.LAND_TAX_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setLandTax(String landTax) {
        this.landTax = landTax == null ? null : landTax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.BANK_ACCOUNT_
     *
     * @return the value of tb_sys_company.BANK_ACCOUNT_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.BANK_ACCOUNT_
     *
     * @param bankAccount the value for tb_sys_company.BANK_ACCOUNT_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.BANK_
     *
     * @return the value of tb_sys_company.BANK_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.BANK_
     *
     * @param bank the value for tb_sys_company.BANK_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.LEVEL_
     *
     * @return the value of tb_sys_company.LEVEL_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.LEVEL_
     *
     * @param level the value for tb_sys_company.LEVEL_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.REMARK1_
     *
     * @return the value of tb_sys_company.REMARK1_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.REMARK1_
     *
     * @param remark1 the value for tb_sys_company.REMARK1_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.REMARK2_
     *
     * @return the value of tb_sys_company.REMARK2_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.REMARK2_
     *
     * @param remark2 the value for tb_sys_company.REMARK2_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.REMARK3_
     *
     * @return the value of tb_sys_company.REMARK3_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.REMARK3_
     *
     * @param remark3 the value for tb_sys_company.REMARK3_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.CREATE_EMP_
     *
     * @return the value of tb_sys_company.CREATE_EMP_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.CREATE_EMP_
     *
     * @param createEmp the value for tb_sys_company.CREATE_EMP_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.CREATE_DATE_
     *
     * @return the value of tb_sys_company.CREATE_DATE_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.CREATE_DATE_
     *
     * @param createDate the value for tb_sys_company.CREATE_DATE_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.UPDATE_DATE_
     *
     * @return the value of tb_sys_company.UPDATE_DATE_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.UPDATE_DATE_
     *
     * @param updateDate the value for tb_sys_company.UPDATE_DATE_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.UPDATE_EMP_
     *
     * @return the value of tb_sys_company.UPDATE_EMP_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.UPDATE_EMP_
     *
     * @param updateEmp the value for tb_sys_company.UPDATE_EMP_
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_company.VERSION
     *
     * @return the value of tb_sys_company.VERSION
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_company.VERSION
     *
     * @param version the value for tb_sys_company.VERSION
     *
     * @mbggenerated Thu Apr 12 10:59:06 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}