package com.qcap.cac.model;

import java.io.Serializable;
import java.util.Date;

public class Department implements Serializable{
	
	
    /**
	 * 
	 */
	private static final long serialVersionUID = -3060708171601586611L;

	/**
    *   主键
     */
    private String departmentId;

    /**
    *   公司别
     */
    private String companyCode;

    /**
    *   部门全称
     */
    private String deptName;
    
    /**
     *   部门简称
      */
     private String shortName;
     
     /**
      *   部门英文简称
       */
      private String code;

    /**
    *   部门层级
     */
    private Integer layer;

    /**
    *   部门代码
     */
    private String deptCode;

    /**
    *   上级部门ID
     */
    private String parentDeptId;

    /**
    *   地址
     */
    private String address;

    /**
    *   删除标示,0未，1已删除
     */
    private String deleteFlag;

    /**
    *   是否有子部门(0无，1有)
     */
    private String haveChild;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.DEPARTMENT_ID_
     *
     * @return the value of tb_sys_department.DEPARTMENT_ID_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.DEPARTMENT_ID_
     *
     * @param departmentId the value for tb_sys_department.DEPARTMENT_ID_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.COMPANY_CODE_
     *
     * @return the value of tb_sys_department.COMPANY_CODE_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.COMPANY_CODE_
     *
     * @param companyCode the value for tb_sys_department.COMPANY_CODE_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.DEPT_NAME_
     *
     * @return the value of tb_sys_department.DEPT_NAME_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.DEPT_NAME_
     *
     * @param deptName the value for tb_sys_department.DEPT_NAME_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.LAYER_
     *
     * @return the value of tb_sys_department.LAYER_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.LAYER_
     *
     * @param layer the value for tb_sys_department.LAYER_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.DEPT_CODE_
     *
     * @return the value of tb_sys_department.DEPT_CODE_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.DEPT_CODE_
     *
     * @param deptCode the value for tb_sys_department.DEPT_CODE_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.PARENT_DEPT_ID_
     *
     * @return the value of tb_sys_department.PARENT_DEPT_ID_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getParentDeptId() {
        return parentDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.PARENT_DEPT_ID_
     *
     * @param parentDeptId the value for tb_sys_department.PARENT_DEPT_ID_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setParentDeptId(String parentDeptId) {
        this.parentDeptId = parentDeptId == null ? null : parentDeptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.ADDRESS_
     *
     * @return the value of tb_sys_department.ADDRESS_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.ADDRESS_
     *
     * @param address the value for tb_sys_department.ADDRESS_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.DELETE_FLAG_
     *
     * @return the value of tb_sys_department.DELETE_FLAG_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.DELETE_FLAG_
     *
     * @param deleteFlag the value for tb_sys_department.DELETE_FLAG_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.HAVE_CHILD_
     *
     * @return the value of tb_sys_department.HAVE_CHILD_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getHaveChild() {
        return haveChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.HAVE_CHILD_
     *
     * @param haveChild the value for tb_sys_department.HAVE_CHILD_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setHaveChild(String haveChild) {
        this.haveChild = haveChild == null ? null : haveChild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.REMARK1_
     *
     * @return the value of tb_sys_department.REMARK1_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.REMARK1_
     *
     * @param remark1 the value for tb_sys_department.REMARK1_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.REMARK2_
     *
     * @return the value of tb_sys_department.REMARK2_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.REMARK2_
     *
     * @param remark2 the value for tb_sys_department.REMARK2_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.REMARK3_
     *
     * @return the value of tb_sys_department.REMARK3_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.REMARK3_
     *
     * @param remark3 the value for tb_sys_department.REMARK3_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.CREATE_EMP_
     *
     * @return the value of tb_sys_department.CREATE_EMP_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.CREATE_EMP_
     *
     * @param createEmp the value for tb_sys_department.CREATE_EMP_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.CREATE_DATE_
     *
     * @return the value of tb_sys_department.CREATE_DATE_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.CREATE_DATE_
     *
     * @param createDate the value for tb_sys_department.CREATE_DATE_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.UPDATE_DATE_
     *
     * @return the value of tb_sys_department.UPDATE_DATE_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.UPDATE_DATE_
     *
     * @param updateDate the value for tb_sys_department.UPDATE_DATE_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.UPDATE_EMP_
     *
     * @return the value of tb_sys_department.UPDATE_EMP_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.UPDATE_EMP_
     *
     * @param updateEmp the value for tb_sys_department.UPDATE_EMP_
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_department.VERSION
     *
     * @return the value of tb_sys_department.VERSION
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_department.VERSION
     *
     * @param version the value for tb_sys_department.VERSION
     *
     * @mbggenerated Thu Apr 12 15:02:15 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}
    
    
}