package com.qcap.cac.model;

import java.io.Serializable;
import java.util.Date;

public class TbAccessLog implements Serializable{
	
    /**
	 * 
	 */
	private static final long serialVersionUID = 483275724630354735L;
	

	/**
    *   主键
     */
    private String tbAccessLogId;

    /**
    *   设备ID
     */
    private String deviceId;

    /**
    *   调用url
     */
    private String url;

    /**
    *   REQUEST
     */
    private String request;

    /**
    *   RESPONSE
     */
    private String response;

    /**
    *   http状态
     */
    private String httpStatus;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   版本
     */
    private Integer version;

    /**
    *   返回信息
     */
    private byte[] info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.TB_ACCESS_LOG_ID_
     *
     * @return the value of tb_access_log.TB_ACCESS_LOG_ID_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public String getTbAccessLogId() {
        return tbAccessLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.TB_ACCESS_LOG_ID_
     *
     * @param tbAccessLogId the value for tb_access_log.TB_ACCESS_LOG_ID_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setTbAccessLogId(String tbAccessLogId) {
        this.tbAccessLogId = tbAccessLogId == null ? null : tbAccessLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.DEVICE_ID_
     *
     * @return the value of tb_access_log.DEVICE_ID_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.DEVICE_ID_
     *
     * @param deviceId the value for tb_access_log.DEVICE_ID_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.URL_
     *
     * @return the value of tb_access_log.URL_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.URL_
     *
     * @param url the value for tb_access_log.URL_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.REQUEST_
     *
     * @return the value of tb_access_log.REQUEST_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.REQUEST_
     *
     * @param request the value for tb_access_log.REQUEST_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setRequest(String request) {
        this.request = request == null ? null : request.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.RESPONSE_
     *
     * @return the value of tb_access_log.RESPONSE_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.RESPONSE_
     *
     * @param response the value for tb_access_log.RESPONSE_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.HTTP_STATUS_
     *
     * @return the value of tb_access_log.HTTP_STATUS_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public String getHttpStatus() {
        return httpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.HTTP_STATUS_
     *
     * @param httpStatus the value for tb_access_log.HTTP_STATUS_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setHttpStatus(String httpStatus) {
        this.httpStatus = httpStatus == null ? null : httpStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.CREATE_EMP_
     *
     * @return the value of tb_access_log.CREATE_EMP_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.CREATE_EMP_
     *
     * @param createEmp the value for tb_access_log.CREATE_EMP_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.CREATE_DATE_
     *
     * @return the value of tb_access_log.CREATE_DATE_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.CREATE_DATE_
     *
     * @param createDate the value for tb_access_log.CREATE_DATE_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.UPDATE_EMP_
     *
     * @return the value of tb_access_log.UPDATE_EMP_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.UPDATE_EMP_
     *
     * @param updateEmp the value for tb_access_log.UPDATE_EMP_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.UPDATE_DATE_
     *
     * @return the value of tb_access_log.UPDATE_DATE_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.UPDATE_DATE_
     *
     * @param updateDate the value for tb_access_log.UPDATE_DATE_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.VERSION
     *
     * @return the value of tb_access_log.VERSION
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.VERSION
     *
     * @param version the value for tb_access_log.VERSION
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_access_log.INFO_
     *
     * @return the value of tb_access_log.INFO_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public byte[] getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_access_log.INFO_
     *
     * @param info the value for tb_access_log.INFO_
     *
     * @mbggenerated Tue Mar 27 18:26:04 CST 2018
     */
    public void setInfo(byte[] info) {
        this.info = info;
    }
}