package com.qcap.cac.model;

import java.io.Serializable;
import java.util.Date;

public class Tbsmi01 implements Serializable{
    /**
	 * @fieldName: serialVersionUID
	 * @fieldType: long
	 * @Description: TODO
	 */
	private static final long serialVersionUID = -8867220866570329173L;

	/**
    *   主键
     */
    private String tbsmi01Id;

    /**
    *   手机号
     */
    private String mobile;

    /**
    *    验证码：6位随机数字
     */
    private String messidtfNo;

    /**
    *   验证码发送时间
     */
    private Date messidtfTime;

    /**
    *   超时时间
     */
    private Date messidtfTimeout;

    /**
    *   用户类型：0前台用户(APP用户)，1后台用户(PC管理端用户)
     */
    private String userType;

    /**
    *   备注1
     */
    private String remark1;

    /**
    *   备注2
     */
    private String remark2;

    /**
    *   备注3
     */
    private String remark3;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.TBSMI01_ID_
     *
     * @return the value of tbsmi01.TBSMI01_ID_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public String getTbsmi01Id() {
        return tbsmi01Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.TBSMI01_ID_
     *
     * @param tbsmi01Id the value for tbsmi01.TBSMI01_ID_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setTbsmi01Id(String tbsmi01Id) {
        this.tbsmi01Id = tbsmi01Id == null ? null : tbsmi01Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.MOBILE_
     *
     * @return the value of tbsmi01.MOBILE_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.MOBILE_
     *
     * @param mobile the value for tbsmi01.MOBILE_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.MESSIDTF_NO_
     *
     * @return the value of tbsmi01.MESSIDTF_NO_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public String getMessidtfNo() {
        return messidtfNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.MESSIDTF_NO_
     *
     * @param messidtfNo the value for tbsmi01.MESSIDTF_NO_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setMessidtfNo(String messidtfNo) {
        this.messidtfNo = messidtfNo == null ? null : messidtfNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.MESSIDTF_TIME_
     *
     * @return the value of tbsmi01.MESSIDTF_TIME_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public Date getMessidtfTime() {
        return messidtfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.MESSIDTF_TIME_
     *
     * @param messidtfTime the value for tbsmi01.MESSIDTF_TIME_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setMessidtfTime(Date messidtfTime) {
        this.messidtfTime = messidtfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.MESSIDTF_TIMEOUT_
     *
     * @return the value of tbsmi01.MESSIDTF_TIMEOUT_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public Date getMessidtfTimeout() {
        return messidtfTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.MESSIDTF_TIMEOUT_
     *
     * @param messidtfTimeout the value for tbsmi01.MESSIDTF_TIMEOUT_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setMessidtfTimeout(Date messidtfTimeout) {
        this.messidtfTimeout = messidtfTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.USER_TYPE_
     *
     * @return the value of tbsmi01.USER_TYPE_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.USER_TYPE_
     *
     * @param userType the value for tbsmi01.USER_TYPE_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.REMARK1_
     *
     * @return the value of tbsmi01.REMARK1_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.REMARK1_
     *
     * @param remark1 the value for tbsmi01.REMARK1_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.REMARK2_
     *
     * @return the value of tbsmi01.REMARK2_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.REMARK2_
     *
     * @param remark2 the value for tbsmi01.REMARK2_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.REMARK3_
     *
     * @return the value of tbsmi01.REMARK3_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.REMARK3_
     *
     * @param remark3 the value for tbsmi01.REMARK3_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.CREATE_EMP_
     *
     * @return the value of tbsmi01.CREATE_EMP_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.CREATE_EMP_
     *
     * @param createEmp the value for tbsmi01.CREATE_EMP_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.CREATE_DATE_
     *
     * @return the value of tbsmi01.CREATE_DATE_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.CREATE_DATE_
     *
     * @param createDate the value for tbsmi01.CREATE_DATE_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.UPDATE_DATE_
     *
     * @return the value of tbsmi01.UPDATE_DATE_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.UPDATE_DATE_
     *
     * @param updateDate the value for tbsmi01.UPDATE_DATE_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.UPDATE_EMP_
     *
     * @return the value of tbsmi01.UPDATE_EMP_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.UPDATE_EMP_
     *
     * @param updateEmp the value for tbsmi01.UPDATE_EMP_
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsmi01.VERSION
     *
     * @return the value of tbsmi01.VERSION
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsmi01.VERSION
     *
     * @param version the value for tbsmi01.VERSION
     *
     * @mbggenerated Fri Apr 13 09:03:04 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}