package com.qcap.cac.model;

import java.util.Date;

public class TbSysLocation {
    /**
    *   主键
     */
    private String id;

    /**
    *   地名
     */
    private String name;

    /**
    *   地名编码
     */
    private String code;

    /**
    *   上级地名ID
     */
    private String pid;

    /**
    *   删除标示,0未，1已删除
     */
    private String deleteFlag;

    /**
    *   备注
     */
    private String remark;

    /**
    *   新增人
     */
    private String createEmp;

    /**
    *   新增时间
     */
    private Date createDate;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.ID_
     *
     * @return the value of tb_sys_location.ID_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.ID_
     *
     * @param id the value for tb_sys_location.ID_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.NAME_
     *
     * @return the value of tb_sys_location.NAME_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.NAME_
     *
     * @param name the value for tb_sys_location.NAME_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.CODE_
     *
     * @return the value of tb_sys_location.CODE_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.CODE_
     *
     * @param code the value for tb_sys_location.CODE_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.PID_
     *
     * @return the value of tb_sys_location.PID_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.PID_
     *
     * @param pid the value for tb_sys_location.PID_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.DELETE_FLAG_
     *
     * @return the value of tb_sys_location.DELETE_FLAG_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.DELETE_FLAG_
     *
     * @param deleteFlag the value for tb_sys_location.DELETE_FLAG_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.REMARK_
     *
     * @return the value of tb_sys_location.REMARK_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.REMARK_
     *
     * @param remark the value for tb_sys_location.REMARK_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.CREATE_EMP_
     *
     * @return the value of tb_sys_location.CREATE_EMP_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.CREATE_EMP_
     *
     * @param createEmp the value for tb_sys_location.CREATE_EMP_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.CREATE_DATE_
     *
     * @return the value of tb_sys_location.CREATE_DATE_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.CREATE_DATE_
     *
     * @param createDate the value for tb_sys_location.CREATE_DATE_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.UPDATE_DATE_
     *
     * @return the value of tb_sys_location.UPDATE_DATE_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.UPDATE_DATE_
     *
     * @param updateDate the value for tb_sys_location.UPDATE_DATE_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.UPDATE_EMP_
     *
     * @return the value of tb_sys_location.UPDATE_EMP_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.UPDATE_EMP_
     *
     * @param updateEmp the value for tb_sys_location.UPDATE_EMP_
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_location.VERSION
     *
     * @return the value of tb_sys_location.VERSION
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_location.VERSION
     *
     * @param version the value for tb_sys_location.VERSION
     *
     * @mbggenerated Wed Apr 25 10:22:10 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}