package com.qcap.cac.model;

import java.io.Serializable;
import java.util.Date;

public class TbSysFile implements Serializable{
	
	 /**
	 * @fieldName: serialVersionUID
	 * @fieldType: long
	 * @Description: TODO
	 */
	private static final long serialVersionUID = -691986623579098630L;

	/**
	    *   主键ID
	     */
	    private String tbFileId;

	    /**
	    *   文件、图片所属组ID
	     */
	    private String groupId;

	    /**
	    *   文件名称
	     */
	    private String fileName;

	    /**
	    *   文件存储路径
	     */
	    private String filePath;

	    /**
	    *   备注
	     */
	    private String remark;

	    /**
	    *   新增人
	     */
	    private String createEmp;

	    /**
	    *   新增时间
	     */
	    private Date createDate;

	    /**
	    *   修改时间
	     */
	    private Date updateDate;

	    /**
	    *   修改人
	     */
	    private String updateEmp;

	    /**
	    *   版本
	     */
	    private Integer version;

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.TB_FILE_ID_
	     *
	     * @return the value of tb_sys_file.TB_FILE_ID_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public String getTbFileId() {
	        return tbFileId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.TB_FILE_ID_
	     *
	     * @param tbFileId the value for tb_sys_file.TB_FILE_ID_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setTbFileId(String tbFileId) {
	        this.tbFileId = tbFileId == null ? null : tbFileId.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.GROUP_ID_
	     *
	     * @return the value of tb_sys_file.GROUP_ID_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public String getGroupId() {
	        return groupId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.GROUP_ID_
	     *
	     * @param groupId the value for tb_sys_file.GROUP_ID_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setGroupId(String groupId) {
	        this.groupId = groupId == null ? null : groupId.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.FILE_NAME_
	     *
	     * @return the value of tb_sys_file.FILE_NAME_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public String getFileName() {
	        return fileName;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.FILE_NAME_
	     *
	     * @param fileName the value for tb_sys_file.FILE_NAME_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setFileName(String fileName) {
	        this.fileName = fileName == null ? null : fileName.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.FILE_PATH_
	     *
	     * @return the value of tb_sys_file.FILE_PATH_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public String getFilePath() {
	        return filePath;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.FILE_PATH_
	     *
	     * @param filePath the value for tb_sys_file.FILE_PATH_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setFilePath(String filePath) {
	        this.filePath = filePath == null ? null : filePath.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.REMARK_
	     *
	     * @return the value of tb_sys_file.REMARK_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public String getRemark() {
	        return remark;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.REMARK_
	     *
	     * @param remark the value for tb_sys_file.REMARK_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setRemark(String remark) {
	        this.remark = remark == null ? null : remark.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.CREATE_EMP_
	     *
	     * @return the value of tb_sys_file.CREATE_EMP_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public String getCreateEmp() {
	        return createEmp;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.CREATE_EMP_
	     *
	     * @param createEmp the value for tb_sys_file.CREATE_EMP_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setCreateEmp(String createEmp) {
	        this.createEmp = createEmp == null ? null : createEmp.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.CREATE_DATE_
	     *
	     * @return the value of tb_sys_file.CREATE_DATE_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public Date getCreateDate() {
	        return createDate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.CREATE_DATE_
	     *
	     * @param createDate the value for tb_sys_file.CREATE_DATE_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setCreateDate(Date createDate) {
	        this.createDate = createDate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.UPDATE_DATE_
	     *
	     * @return the value of tb_sys_file.UPDATE_DATE_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public Date getUpdateDate() {
	        return updateDate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.UPDATE_DATE_
	     *
	     * @param updateDate the value for tb_sys_file.UPDATE_DATE_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setUpdateDate(Date updateDate) {
	        this.updateDate = updateDate;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.UPDATE_EMP_
	     *
	     * @return the value of tb_sys_file.UPDATE_EMP_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public String getUpdateEmp() {
	        return updateEmp;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.UPDATE_EMP_
	     *
	     * @param updateEmp the value for tb_sys_file.UPDATE_EMP_
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setUpdateEmp(String updateEmp) {
	        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column tb_sys_file.VERSION
	     *
	     * @return the value of tb_sys_file.VERSION
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public Integer getVersion() {
	        return version;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column tb_sys_file.VERSION
	     *
	     * @param version the value for tb_sys_file.VERSION
	     *
	     * @mbggenerated Wed May 23 17:32:00 CST 2018
	     */
	    public void setVersion(Integer version) {
	        this.version = version;
	    }
}