package com.qcap.cac.model;

import java.io.Serializable;
import java.util.Date;

public class TbSysPosition implements Serializable{
	
    /**
	 * @fieldName: serialVersionUID
	 * @fieldType: long
	 * @Description: TODO
	 */
	private static final long serialVersionUID = 5834560854182097744L;

	/**
    *   主键
     */
    private String positionId;

    /**
    *   公司别
     */
    private String companyCode;

    /**
    *   职位名称
     */
    private String positionName;

    /**
    *   职位级别1员工，2科长，3部长，4等等，需要客户提供相关信息
     */
    private String positionLevel;

    /**
    *   上班开始时间
     */
    private Date startTime;

    /**
    *   下班结束时间
     */
    private Date endTime;

    /**
    *   删除标示,0未删除，1已删除
     */
    private String deleteFlag;

    /**
    *   创建人
     */
    private String createEmp;

    /**
    *   创建时间
     */
    private Date createDate;

    /**
    *   修改人
     */
    private String updateEmp;

    /**
    *   修改时间
     */
    private Date updateDate;

    /**
    *   版本
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.POSITION_ID_
     *
     * @return the value of tb_sys_position.POSITION_ID_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public String getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.POSITION_ID_
     *
     * @param positionId the value for tb_sys_position.POSITION_ID_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setPositionId(String positionId) {
        this.positionId = positionId == null ? null : positionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.COMPANY_CODE_
     *
     * @return the value of tb_sys_position.COMPANY_CODE_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.COMPANY_CODE_
     *
     * @param companyCode the value for tb_sys_position.COMPANY_CODE_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.POSITION_NAME_
     *
     * @return the value of tb_sys_position.POSITION_NAME_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.POSITION_NAME_
     *
     * @param positionName the value for tb_sys_position.POSITION_NAME_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.POSITION_LEVEL_
     *
     * @return the value of tb_sys_position.POSITION_LEVEL_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public String getPositionLevel() {
        return positionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.POSITION_LEVEL_
     *
     * @param positionLevel the value for tb_sys_position.POSITION_LEVEL_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setPositionLevel(String positionLevel) {
        this.positionLevel = positionLevel == null ? null : positionLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.START_TIME_
     *
     * @return the value of tb_sys_position.START_TIME_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.START_TIME_
     *
     * @param startTime the value for tb_sys_position.START_TIME_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.END_TIME_
     *
     * @return the value of tb_sys_position.END_TIME_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.END_TIME_
     *
     * @param endTime the value for tb_sys_position.END_TIME_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.DELETE_FLAG_
     *
     * @return the value of tb_sys_position.DELETE_FLAG_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.DELETE_FLAG_
     *
     * @param deleteFlag the value for tb_sys_position.DELETE_FLAG_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.CREATE_EMP_
     *
     * @return the value of tb_sys_position.CREATE_EMP_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.CREATE_EMP_
     *
     * @param createEmp the value for tb_sys_position.CREATE_EMP_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.CREATE_DATE_
     *
     * @return the value of tb_sys_position.CREATE_DATE_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.CREATE_DATE_
     *
     * @param createDate the value for tb_sys_position.CREATE_DATE_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.UPDATE_EMP_
     *
     * @return the value of tb_sys_position.UPDATE_EMP_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.UPDATE_EMP_
     *
     * @param updateEmp the value for tb_sys_position.UPDATE_EMP_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.UPDATE_DATE_
     *
     * @return the value of tb_sys_position.UPDATE_DATE_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.UPDATE_DATE_
     *
     * @param updateDate the value for tb_sys_position.UPDATE_DATE_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_position.VERSION_
     *
     * @return the value of tb_sys_position.VERSION_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_position.VERSION_
     *
     * @param version the value for tb_sys_position.VERSION_
     *
     * @mbggenerated Tue Apr 17 16:41:38 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}