package com.qcap.cac.model;

import java.io.Serializable;
import java.util.Date;

public class TbUser implements Serializable{
	
	
    /**
	 * @fieldName: serialVersionUID
	 * @fieldType: long
	 * @Description: TODO
	 */
	private static final long serialVersionUID = -3526751843656909982L;

	/**
    *   主键id
     */
    private String id;

    /**
    *   密码
     */
    private String password;

    /**
    *   账号
     */
    private String account;

    /**
    *   md5密码盐
     */
    private String salt;

    /**
    *   公司别
     */
    private String companyCode;

    /**
    *   部门ID
     */
    private String departmentId;

    /**
    *   
     */
    private String communityId;

    /**
    *   性别0女，1男
     */
    private Integer sex;

    /**
    *   名字
     */
    private String name;

    /**
    *   状态(1：启用  2：冻结  3：删除）
     */
    private Integer status;

    /**
    *   
     */
    private String phone;

    /**
    *   邮箱
     */
    private String mail;

    /**
    *   用户类型：W pc端用户 A手机端用户
     */
    private String userType;

    /**
    *   
     */
    private Date birthday;

    /**
    *   头像
     */
    private String img;

    /**
    *   
     */
    private String idCard;

    /**
    *   
     */
    private String address;

    /**
    *   
     */
    private String startDate;

    /**
    *   
     */
    private String endDate;

    /**
    *   最新地址
     */
    private String newAddress;

    /**
    *   
     */
    private String race;

    /**
    *   
     */
    private String management;

    /**
    *   
     */
    private String remark;

    /**
    *   创建时间
     */
    private Date createTime;

    /**
    *   
     */
    private String createEmp;

    /**
    *   
     */
    private Date updateTime;

    /**
    *   
     */
    private String updateEmp;

    /**
    *   保留字段
     */
    private Integer version;

    /**
    *   职位ID
     */
    private String positionId;
     
    /**
     *   学历
     */
    private String education;
    
    /**
     *   职业
     */
    private String career;
    
    /**
     *   收入
     */
    private String income;
    
    /**
     * 业务角色分类
     */
    private String managerType;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ID_
     *
     * @return the value of tb_user.ID_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ID_
     *
     * @param id the value for tb_user.ID_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.PASSWORD_
     *
     * @return the value of tb_user.PASSWORD_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.PASSWORD_
     *
     * @param password the value for tb_user.PASSWORD_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ACCOUNT_
     *
     * @return the value of tb_user.ACCOUNT_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ACCOUNT_
     *
     * @param account the value for tb_user.ACCOUNT_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.SALT_
     *
     * @return the value of tb_user.SALT_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.SALT_
     *
     * @param salt the value for tb_user.SALT_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.COMPANY_CODE_
     *
     * @return the value of tb_user.COMPANY_CODE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.COMPANY_CODE_
     *
     * @param companyCode the value for tb_user.COMPANY_CODE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.DEPARTMENT_ID_
     *
     * @return the value of tb_user.DEPARTMENT_ID_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.DEPARTMENT_ID_
     *
     * @param departmentId the value for tb_user.DEPARTMENT_ID_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.COMMUNITY_ID_
     *
     * @return the value of tb_user.COMMUNITY_ID_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.COMMUNITY_ID_
     *
     * @param communityId the value for tb_user.COMMUNITY_ID_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setCommunityId(String communityId) {
        this.communityId = communityId == null ? null : communityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.SEX_
     *
     * @return the value of tb_user.SEX_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.SEX_
     *
     * @param sex the value for tb_user.SEX_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.NAME_
     *
     * @return the value of tb_user.NAME_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.NAME_
     *
     * @param name the value for tb_user.NAME_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.STATUS_
     *
     * @return the value of tb_user.STATUS_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.STATUS_
     *
     * @param status the value for tb_user.STATUS_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.PHONE_
     *
     * @return the value of tb_user.PHONE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.PHONE_
     *
     * @param phone the value for tb_user.PHONE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MAIL_
     *
     * @return the value of tb_user.MAIL_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MAIL_
     *
     * @param mail the value for tb_user.MAIL_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.USER_TYPE_
     *
     * @return the value of tb_user.USER_TYPE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.USER_TYPE_
     *
     * @param userType the value for tb_user.USER_TYPE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.BIRTHDAY_
     *
     * @return the value of tb_user.BIRTHDAY_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.BIRTHDAY_
     *
     * @param birthday the value for tb_user.BIRTHDAY_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.IMG_
     *
     * @return the value of tb_user.IMG_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.IMG_
     *
     * @param img the value for tb_user.IMG_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ID_CARD_
     *
     * @return the value of tb_user.ID_CARD_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ID_CARD_
     *
     * @param idCard the value for tb_user.ID_CARD_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ADDRESS_
     *
     * @return the value of tb_user.ADDRESS_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ADDRESS_
     *
     * @param address the value for tb_user.ADDRESS_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.START_DATE_
     *
     * @return the value of tb_user.START_DATE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.START_DATE_
     *
     * @param startDate the value for tb_user.START_DATE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.END_DATE_
     *
     * @return the value of tb_user.END_DATE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.END_DATE_
     *
     * @param endDate the value for tb_user.END_DATE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.NEW_ADDRESS_
     *
     * @return the value of tb_user.NEW_ADDRESS_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getNewAddress() {
        return newAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.NEW_ADDRESS_
     *
     * @param newAddress the value for tb_user.NEW_ADDRESS_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setNewAddress(String newAddress) {
        this.newAddress = newAddress == null ? null : newAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.RACE_
     *
     * @return the value of tb_user.RACE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getRace() {
        return race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.RACE_
     *
     * @param race the value for tb_user.RACE_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setRace(String race) {
        this.race = race == null ? null : race.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.MANAGEMENT_
     *
     * @return the value of tb_user.MANAGEMENT_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getManagement() {
        return management;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.MANAGEMENT_
     *
     * @param management the value for tb_user.MANAGEMENT_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setManagement(String management) {
        this.management = management == null ? null : management.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.REMARK_
     *
     * @return the value of tb_user.REMARK_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.REMARK_
     *
     * @param remark the value for tb_user.REMARK_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.CREATE_TIME_
     *
     * @return the value of tb_user.CREATE_TIME_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.CREATE_TIME_
     *
     * @param createTime the value for tb_user.CREATE_TIME_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.CREATE_EMP_
     *
     * @return the value of tb_user.CREATE_EMP_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.CREATE_EMP_
     *
     * @param createEmp the value for tb_user.CREATE_EMP_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.UPDATE_TIME_
     *
     * @return the value of tb_user.UPDATE_TIME_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.UPDATE_TIME_
     *
     * @param updateTime the value for tb_user.UPDATE_TIME_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.UPDATE_EMP_
     *
     * @return the value of tb_user.UPDATE_EMP_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.UPDATE_EMP_
     *
     * @param updateEmp the value for tb_user.UPDATE_EMP_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.VERSION_
     *
     * @return the value of tb_user.VERSION_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.VERSION_
     *
     * @param version the value for tb_user.VERSION_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.POSITION_ID_
     *
     * @return the value of tb_user.POSITION_ID_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public String getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.POSITION_ID_
     *
     * @param positionId the value for tb_user.POSITION_ID_
     *
     * @mbggenerated Fri Apr 20 10:31:35 CST 2018
     */
    public void setPositionId(String positionId) {
        this.positionId = positionId == null ? null : positionId.trim();
    }


	public String getEducation() {
		return education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getCareer() {
		return career;
	}

	public void setCareer(String career) {
		this.career = career;
	}

	public String getIncome() {
		return income;
	}

	public void setIncome(String income) {
		this.income = income;
	}

	/**
	 * @return the managerType
	 */
	public String getManagerType() {
		return managerType;
	}

	/**
	 * @param managerType the managerType to set
	 */
	public void setManagerType(String managerType) {
		this.managerType = managerType;
	}

	
}