package com.qcap.cac.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 用户额度表
 * @author wangtianxing
 *
 */
public class TbUserLimit implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 7565490547287372713L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.USER_LIMIT_ID_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private String userLimitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.USER_ID_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.MAX_LIMIT_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private BigDecimal maxLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.AVAILABLE_LIMIT_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private BigDecimal availableLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.COST_LIMIT_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private BigDecimal costLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.PAY_PSD_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private String payPsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.REMARK_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.CREATE_EMP_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private String createEmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.CREATE_DATE_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.UPDATE_EMP_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private String updateEmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.UPDATE_DATE_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_limit.VERSION_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.USER_LIMIT_ID_
     *
     * @return the value of tb_user_limit.USER_LIMIT_ID_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public String getUserLimitId() {
        return userLimitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.USER_LIMIT_ID_
     *
     * @param userLimitId the value for tb_user_limit.USER_LIMIT_ID_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setUserLimitId(String userLimitId) {
        this.userLimitId = userLimitId == null ? null : userLimitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.USER_ID_
     *
     * @return the value of tb_user_limit.USER_ID_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.USER_ID_
     *
     * @param userId the value for tb_user_limit.USER_ID_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.MAX_LIMIT_
     *
     * @return the value of tb_user_limit.MAX_LIMIT_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public BigDecimal getMaxLimit() {
        return maxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.MAX_LIMIT_
     *
     * @param maxLimit the value for tb_user_limit.MAX_LIMIT_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setMaxLimit(BigDecimal maxLimit) {
        this.maxLimit = maxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.AVAILABLE_LIMIT_
     *
     * @return the value of tb_user_limit.AVAILABLE_LIMIT_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public BigDecimal getAvailableLimit() {
        return availableLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.AVAILABLE_LIMIT_
     *
     * @param availableLimit the value for tb_user_limit.AVAILABLE_LIMIT_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setAvailableLimit(BigDecimal availableLimit) {
        this.availableLimit = availableLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.COST_LIMIT_
     *
     * @return the value of tb_user_limit.COST_LIMIT_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public BigDecimal getCostLimit() {
        return costLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.COST_LIMIT_
     *
     * @param costLimit the value for tb_user_limit.COST_LIMIT_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setCostLimit(BigDecimal costLimit) {
        this.costLimit = costLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.PAY_PSD_
     *
     * @return the value of tb_user_limit.PAY_PSD_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public String getPayPsd() {
        return payPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.PAY_PSD_
     *
     * @param payPsd the value for tb_user_limit.PAY_PSD_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setPayPsd(String payPsd) {
        this.payPsd = payPsd == null ? null : payPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.REMARK_
     *
     * @return the value of tb_user_limit.REMARK_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.REMARK_
     *
     * @param remark the value for tb_user_limit.REMARK_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.CREATE_EMP_
     *
     * @return the value of tb_user_limit.CREATE_EMP_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.CREATE_EMP_
     *
     * @param createEmp the value for tb_user_limit.CREATE_EMP_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp == null ? null : createEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.CREATE_DATE_
     *
     * @return the value of tb_user_limit.CREATE_DATE_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.CREATE_DATE_
     *
     * @param createDate the value for tb_user_limit.CREATE_DATE_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.UPDATE_EMP_
     *
     * @return the value of tb_user_limit.UPDATE_EMP_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public String getUpdateEmp() {
        return updateEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.UPDATE_EMP_
     *
     * @param updateEmp the value for tb_user_limit.UPDATE_EMP_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setUpdateEmp(String updateEmp) {
        this.updateEmp = updateEmp == null ? null : updateEmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.UPDATE_DATE_
     *
     * @return the value of tb_user_limit.UPDATE_DATE_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.UPDATE_DATE_
     *
     * @param updateDate the value for tb_user_limit.UPDATE_DATE_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_limit.VERSION_
     *
     * @return the value of tb_user_limit.VERSION_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_limit.VERSION_
     *
     * @param version the value for tb_user_limit.VERSION_
     *
     * @mbggenerated Fri Apr 27 08:38:03 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}